### ISSUE TITLE
Uncaught TypeError: Arguments to path.join must be strings

### ISSUE THREAD

**Issue by ja-mes** [imdone/imdone-atom#11]
#### Steps to reproduce

1. Open Atom.
2. Open imdone by pressing <kbd>ctrl</kbd>+<kbd>shift</kbd>+<kbd>p</kbd>, typing imdone and pressing enter.
3. Close the imdone tab.

**Atom Version**: 1.0.5
**System**: Ubuntu 14.04.3
**Thrown From**: [imdone-atom](https://github.com/imdone/imdone-atom) package, v1.1.13

### Stack Trace

Uncaught TypeError: Arguments to path.join must be strings

```
At /home/james/.atom/packages/imdone-atom/node_modules/imdone-core/lib/repository.js:549

TypeError: Arguments to path.join must be strings
    at Object.posix.join (path.js:449:13)
    at Repository.getFullPath (/home/james/.atom/packages/imdone-atom/node_modules/imdone-core/lib/repository.js:343:15)
    at /home/james/.atom/packages/imdone-atom/node_modules/imdone-core/lib/mixins/repo-fs-store.js:84:36
    at FSReqWrap.oncomplete (fs.js:77:15)
```

### Commands

```
     -0:06.1.0 command-palette:toggle (atom-text-editor.editor.is-focused.vim-mode.normal-mode)
     -0:04.8.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:04.8.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:04.3.0 command-palette:toggle (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:03.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:03.0 imdone-atom:tasks (atom-text-editor.editor.vim-mode.normal-mode)
     -0:00.6.0 core:close (atom-pane.pane.active)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "monokai"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-handlebars, v1.1.0
color-picker, v2.0.11
imdone-atom, v1.1.13
less-than-slash, v0.7.0
linter, v1.3.2
linter-jshint, v1.1.4
monokai, v0.17.0
vim-mode, v0.57.0
vim-surround, v0.8.0

# Dev
No dev packages
```

**Comment by piascikj** [comment]
Did you have any files open?

**Comment by ja-mes** [comment]
Yes, I did have open files, but this appears to be happening regardless.

**Comment by piascikj** [comment]
Can you upgrade to 1.1.16?  I made a patch that gives us more debug info when this error occurs.

**Comment by ja-mes** [comment]
After upgrading to 1.1.16, I am experiencing a different error when closing imdone.

**Atom Version**: 1.0.5
**System**: Ubuntu 14.04.3
**Thrown From**: [imdone-atom](https://github.com/imdone/imdone-atom) package, v1.1.16


### Stack Trace

Uncaught TypeError: Arguments to path.resolve must be strings

```
At path.js:400

TypeError: Arguments to path.resolve must be strings
    at Object.posix.resolve (path.js:400:13)
    at Object.posix.relative (path.js:466:16)
    at Repository.getRelativePath (/home/james/.atom/packages/imdone-atom/node_modules/imdone-core/lib/repository.js:359:15)
    at /home/james/.atom/packages/imdone-atom/node_modules/imdone-core/lib/mixins/repo-fs-store.js:188:21
    at replenish (/usr/share/atom/resources/app.asar/node_modules/request/node_modules/form-data/node_modules/async/lib/async.js:191:21)
    at /usr/share/atom/resources/app.asar/node_modules/request/node_modules/form-data/node_modules/async/lib/async.js:203:33
    at /home/james/.atom/packages/imdone-atom/node_modules/imdone-core/lib/mixins/repo-fs-store.js:209:11
    at /home/james/.atom/packages/imdone-atom/node_modules/imdone-core/lib/mixins/repo-fs-store.js:86:11
    at /home/james/.atom/packages/imdone-atom/node_modules/imdone-core/lib/tools.js:220:24
    at FSReqWrap.oncomplete (fs.js:77:15)
```

### Commands

```
     -0:59.5.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.theme-monokai.theme-one-dark-ui)
     -0:51.6.0 command-palette:toggle (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:50 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:50 imdone-atom:tasks (atom-text-editor.editor.vim-mode.normal-mode)
     -0:40.5.0 core:close (atom-pane.pane.active)
     -0:38.8.0 vim-mode:move-up (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:15.5.0 settings-view:open (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:13.9.0 core:close (div.settings-view.pane-item)
     -0:10.9.0 command-palette:toggle (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
  3x -0:09.1.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:06.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:06.1.0 imdone-atom:tasks (atom-text-editor.editor.vim-mode.normal-mode)
     -0:01.6.0 core:close (atom-pane.pane.active)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "monokai"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-handlebars, v1.1.0
color-picker, v2.0.11
imdone-atom, v1.1.16
less-than-slash, v0.7.0
linter, v1.3.4
linter-jshint, v1.1.5
monokai, v0.17.0
vim-mode, v0.57.0
vim-surround, v0.8.0

# Dev
No dev packages
```

**Comment by piascikj** [comment]
Is it working for you otherwise?  It seems like the project path is getting clobbered.  I'll take a look, but in the meantime can you upgrade so I can work in master?

**Comment by piascikj** [comment]
After you upgrade, please log the issue again, so I can see the stack.

**Comment by ja-mes** [comment]
After upgrading, I am getting these two errors.

**Atom Version**: 1.0.6
**System**: Ubuntu 14.04.3
**Thrown From**: [imdone-atom](https://github.com/imdone/imdone-atom) package, v1.1.18


### Stack Trace

Uncaught Error: Error getting full path for file:%s and repo path:%s

```
At /home/james/.atom/packages/imdone-atom/node_modules/imdone-core/lib/repository.js:347

Error: Error getting full path for file:%s and repo path:%s
    at Repository.getFullPath (/home/james/.atom/packages/imdone-atom/node_modules/imdone-core/lib/repository.js:347:11)
    at /home/james/.atom/packages/imdone-atom/node_modules/imdone-core/lib/mixins/repo-fs-store.js:97:36
    at FSReqWrap.oncomplete (fs.js:77:15)
```

### Commands

```
     -0:36.1.0 command-palette:toggle (atom-text-editor.editor.is-focused.vim-mode.normal-mode)
     -0:34.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:34.8.0 imdone-atom:tasks (atom-text-editor.editor.vim-mode.normal-mode)
     -0:32.2.0 core:close (atom-pane.pane.active)
     -0:07.8.0 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:05.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:05.2.0 vim-mode:reset-normal-mode (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:05.1.0 core:save (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:04.6.0 command-palette:toggle (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:03.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:03.6.0 imdone-atom:tasks (atom-text-editor.editor.vim-mode.normal-mode)
     -0:01.4.0 core:close (atom-pane.pane.active)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "monokai"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-handlebars, v1.1.0
color-picker, v2.0.11
imdone-atom, v1.1.18
less-than-slash, v0.7.0
linter, v1.3.4
linter-jshint, v1.1.5
monokai, v0.17.0
vim-mode, v0.57.0
vim-surround, v0.8.0

# Dev
No dev packages
```
<hr>

**Atom Version**: 1.0.6
**System**: Ubuntu 14.04.3
**Thrown From**: [imdone-atom](https://github.com/imdone/imdone-atom) package, v1.1.18


### Stack Trace

Uncaught TypeError: Arguments to path.resolve must be strings

```
At path.js:400

TypeError: Arguments to path.resolve must be strings
    at Object.posix.resolve (path.js:400:13)
    at Object.posix.relative (path.js:466:16)
    at Repository.getRelativePath (/home/james/.atom/packages/imdone-atom/node_modules/imdone-core/lib/repository.js:359:15)
    at /home/james/.atom/packages/imdone-atom/node_modules/imdone-core/lib/mixins/repo-fs-store.js:201:21
    at replenish (/usr/share/atom/resources/app.asar/node_modules/request/node_modules/form-data/node_modules/async/lib/async.js:191:21)
    at /usr/share/atom/resources/app.asar/node_modules/request/node_modules/form-data/node_modules/async/lib/async.js:203:33
    at /home/james/.atom/packages/imdone-atom/node_modules/imdone-core/lib/mixins/repo-fs-store.js:222:11
    at /home/james/.atom/packages/imdone-atom/node_modules/imdone-core/lib/mixins/repo-fs-store.js:99:11
    at /home/james/.atom/packages/imdone-atom/node_modules/imdone-core/lib/tools.js:220:24
    at FSReqWrap.oncomplete (fs.js:77:15)
```

### Commands

```
     -0:36.1.0 command-palette:toggle (atom-text-editor.editor.is-focused.vim-mode.normal-mode)
     -0:34.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:34.8.0 imdone-atom:tasks (atom-text-editor.editor.vim-mode.normal-mode)
     -0:32.2.0 core:close (atom-pane.pane.active)
     -0:07.8.0 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:05.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:05.2.0 vim-mode:reset-normal-mode (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:05.1.0 core:save (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:04.6.0 command-palette:toggle (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:03.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:03.6.0 imdone-atom:tasks (atom-text-editor.editor.vim-mode.normal-mode)
     -0:01.4.0 core:close (atom-pane.pane.active)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "monokai"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-handlebars, v1.1.0
color-picker, v2.0.11
imdone-atom, v1.1.18
less-than-slash, v0.7.0
linter, v1.3.4
linter-jshint, v1.1.5
monokai, v0.17.0
vim-mode, v0.57.0
vim-surround, v0.8.0

# Dev
No dev packages
```

**Comment by piascikj** [comment]
Would you mind doing a hangout to debug this?
