### ISSUE TITLE
Uncaught TypeError: Cannot read property 'hidden' of undefined

### ISSUE THREAD

**Issue by kferran** [imdone/imdone-atom#15]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.5
**System**: Mac OS X 10.10.4
**Thrown From**: [imdone-atom](https://github.com/imdone/imdone-atom) package, v1.1.15

### Stack Trace

Uncaught TypeError: Cannot read property 'hidden' of undefined

```
At /Users/ferraky/.atom/packages/imdone-atom/lib/menu-view.coffee:61

TypeError: Cannot read property 'hidden' of undefined
  at HTMLSpanElement.<anonymous> (/Users/ferraky/.atom/packages/imdone-atom/lib/menu-view.coffee:61:29)
  at space-pen-div.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
  at space-pen-div.elemData.handle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)

```

### Commands

```
     -0:15.7.0 core:save (a.delete-list)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-material-ui",
      "atom-material-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-material-syntax, v0.2.1
atom-material-ui, v0.5.13
atom-wordpress, v0.3.0
autocomplete-php, v0.3.6
color-picker, v2.0.11
emmet, v2.3.12
gulp-snippets, v0.6.1
imdone-atom, v1.1.15
language-SCSS, v0.4.0
language-vue-component, v0.2.0
php-twig, v4.0.0

# Dev
No dev packages
```

**Comment by piascikj** [comment]
Can you provide some details?  What was the list you were trying to show/hide called?

**Comment by piascikj** [comment]
Can you give me some details?  What were you doing when you received this error?
