### ISSUE TITLE
Uncaught TypeError: Cannot read property 'lists' of undefined

### ISSUE THREAD

**Issue by battlemidget** [imdone/imdone-atom#16]
[Enter steps to reproduce below:]

1. Load a project
2. Run imdone to query list of todos, fixmes 

**Atom Version**: 1.0.5
**System**: Ubuntu 15.04
**Thrown From**: [imdone-atom](https://github.com/imdone/imdone-atom) package, v1.1.15

### Stack Trace

Uncaught TypeError: Cannot read property 'lists' of undefined

```
At /home/adam/.atom/packages/imdone-atom/node_modules/imdone-core/lib/repository.js:270

TypeError: Cannot read property 'lists' of undefined
    at Repository.getLists (/home/adam/.atom/packages/imdone-atom/node_modules/imdone-core/lib/repository.js:270:26)
    at Repository.listExists (/home/adam/.atom/packages/imdone-atom/node_modules/imdone-core/lib/repository.js:297:28)
    at File.taskFoundListener (/home/adam/.atom/packages/imdone-atom/node_modules/imdone-core/lib/repository.js:203:15)
    at emitOne (events.js:77:13)
    at File.emit (events.js:166:7)
    at File.extractCodeStyleTasks (/home/adam/.atom/packages/imdone-atom/node_modules/imdone-core/lib/file.js:342:12)
    at File.extractTasksInCodeFile (/home/adam/.atom/packages/imdone-atom/node_modules/imdone-core/lib/file.js:390:10)
    at File.extractTasks (/home/adam/.atom/packages/imdone-atom/node_modules/imdone-core/lib/file.js:512:10)
    at extract (/home/adam/.atom/packages/imdone-atom/node_modules/imdone-core/lib/repository.js:478:10)
    at Repository.extractTasks (/home/adam/.atom/packages/imdone-atom/node_modules/imdone-core/lib/repository.js:489:10)
    at /home/adam/.atom/packages/imdone-atom/node_modules/imdone-core/lib/repository.js:568:12
    at /home/adam/.atom/packages/imdone-atom/node_modules/imdone-core/lib/mixins/repo-fs-store.js:340:9
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:379:3)
```

### Commands

```
     -0:45 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:38.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:38.8.0 todo-show:find-in-project (atom-text-editor.editor)
     -0:09.1.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:07.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:07.0 imdone-atom:tasks (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true,
    "disabledPackages": [
      "go-format",
      "markdown-preview",
      "atom-rails",
      "archive-view",
      "background-tips",
      "link",
      "metrics",
      "welcome",
      "linter-rubocop",
      "linter-haml"
    ]
  }
}
```

### Installed Packages

```coffee
# User
Stylus, v1.0.0
atom-handlebars, v1.1.0
autocomplete-paths, v1.0.2
autocomplete-python, v0.5.3
autocomplete-ruby, v0.1.0
color-picker, v2.0.11
editorconfig, v1.0.1
file-icons, v1.6.3
gulp-snippets, v0.6.1
imdone-atom, v1.1.15
javascript-snippets, v1.0.0
language-haml, v0.21.0
language-jade, v0.6.2
language-restructuredtext, v0.7.0
language-slim, v0.5.0
linter, v1.3.2
linter-eslint, v3.0.2
linter-flake8, v1.6.0
linter-pep8, v1.0.1
linter-stylint, v2.0.0
pigments, v0.9.3
ruby-block, v0.3.5
todo-show, v0.13.0
travis-ci-status, v0.16.0

# Dev
No dev packages
```

**Comment by piascikj** [comment]
Can you give me any more details?  Did .imdone/config.json get created at the root of your project?

**Comment by wonderbeyond** [comment]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.7
**System**: Ubuntu 14.04.3
**Thrown From**: [imdone-atom](https://github.com/imdone/imdone-atom) package, v1.1.39


### Stack Trace

Uncaught SyntaxError: Unexpected token u

```
At file:///usr/share/atom/resources/app.asar/static/index.html#%7B%22locationsToOpen%22%3A%5B%7B%22pathToOpen%22%3A%22%2Fhome%2Fwonder%2Fprojects%2Fimage-view%22%7D%5D%2C%22bootstrapScript%22%3A%22%2Fusr%2Fshare%2Fatom%2Fresources%2Fapp.asar%2Fsrc%2Fwindow-bootstrap.js%22%2C%22resourcePath%22%3A%22%2Fusr%2Fshare%2Fatom%2Fresources%2Fapp.asar%22%2C%22devMode%22%3Afalse%2C%22safeMode%22%3Afalse%2C%22appVersion%22%3A%221.0.7%22%2C%22shellLoadTime%22%3A388%2C%22initialPaths%22%3A%5B%22%2Fhome%2Fwonder%2Fprojects%2Fimage-view%22%5D%7D:1

SyntaxError: Unexpected token u
  at Object.parse (native)
  at /home/wonder/.atom/packages/imdone-atom/node_modules/imdone-core/lib/mixins/repo-fs-store.js:151:33
  at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:379:3)

```

### Commands

```
     -0:24.5.0 core:close (atom-pane.pane.active)
     -0:02.3.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:00.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:00.5.0 imdone-atom:tasks (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "projectHome": "/home/wonder/projects",
    "themes": [
      "atom-dark-ui",
      "one-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
emmet-simplified, v2.5.0
image-view, v0.55.0
imdone-atom, v1.1.39
minimap, v4.13.3

# Dev
No dev packages
```

**Comment by piascikj** [comment]
@wonderbeyond Can you attach your .imdone/config.json to this issue?

**Comment by wonderbeyond** [comment]
@piascikj I got to know imdone in atom blog just now, unable to play well, then I disable the package and remove d .imdone dir.

I only saw "undefined" in .imdone/config.json before remove.

**Comment by piascikj** [comment]
Thanks!  That helps.

**Comment by wonderbeyond** [comment]
@piascikj That's good news.

**Comment by piascikj** [comment]
@wonderbeyond Can you give it another shot?  I wrapped the JSON.parse in a try catch in case we get bad json.

**Comment by wonderbeyond** [comment]
@piascikj, Now I get this:



[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.7
**System**: Ubuntu 14.04.3
**Thrown From**: [imdone-atom](https://github.com/imdone/imdone-atom) package, v1.1.42


### Stack Trace

Uncaught TypeError: Cannot read property 'push' of undefined

```
At /home/wonder/.atom/packages/imdone-atom/node_modules/imdone-core/lib/repository.js:438

TypeError: Cannot read property 'push' of undefined
    at /home/wonder/.atom/packages/imdone-atom/node_modules/imdone-core/lib/repository.js:438:19
    at /home/wonder/.atom/packages/imdone-atom/node_modules/imdone-core/lib/mixins/repo-fs-store.js:104:11
    at /home/wonder/.atom/packages/imdone-atom/node_modules/imdone-core/lib/tools.js:220:24
    at FSReqWrap.oncomplete (fs.js:77:15)
```

### Commands

```
     -0:53.6.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:49.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:49.4.0 imdone-atom:tasks (atom-text-editor.editor)
     -0:37.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:11.3.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:11.3.0 core:cancel (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "projectHome": "/home/wonder/projects",
    "themes": [
      "atom-dark-ui",
      "one-dark-syntax"
    ]
  },
  "imdone-atom": {}
}
```

### Installed Packages

```coffee
# User
emmet-simplified, v2.5.0
image-view, v0.55.0
imdone-atom, v1.1.42
minimap, v4.13.4

# Dev
No dev packages
```

**Comment by wonderbeyond** [comment]
wonder@ws:~/projects/image-view@master$ cat .imdone/config.json 
```json
{
  "exclude": [
    "^(node_modules|bower_components|\\.imdone|target|build|dist|logs)[\\/\\\\]?|\\.(git|svn|hg|npmignore)|\\~$|\\.(jpg|png|gif|swp|ttf|otf)$"
  ],
  "watcher": true,
  "code": {
    "include_lists": [
      "TODO",
      "DOING",
      "DONE",
      "PLANNING",
      "FIXME",
      "ARCHIVE",
      "HACK",
      "CHANGED",
      "XXX",
      "IDEA",
      "NOTE",
      "REVIEW"
    ]
  },
  "lists": [
    {
      "name": "TODO",
      "hidden": false
    }
  ],
  "marked": {
    "gfm": true,
    "tables": true,
    "breaks": false,
    "pedantic": false,
    "smartLists": true,
    "langPrefix": "language-"
  }
}
```

**Comment by piascikj** [comment]
This is troubling...  [repository,js line #438](https://github.com/imdone/imdone-core/blob/master/lib/repository.js#L438) is pushing to an array that was created at construction.  Very odd.  Can you try uninstalling and reinstalling.  My only other thought is there may be something causing the repo to get destroyed in the middle of this process.

**Comment by wonderbeyond** [comment]
I just quit and reopen my Atom, then no errors occurs. Thanks!

I guess maybe Atom applied serialized data from old version of package to new version, then went wrong.

**Comment by onetrev** [comment]
When I click the "I Need Another List" button I still get this error unfortunately. :(

Windows 10; Atom 1.1.0. 

Also it chucks me an unreported error while I am adding after I submit this.

**Comment by jeremytwfortune** [comment]
Also getting this `TypeError` :cry: It comes bundled with this, which I can also post, if needed.

```
Uncaught TypeError: Cannot set property 'Sortable1446991898354' of null
```

### Reproduction 

 1. Right click on repo, show tasks
 2. Open "tools baby!"
 3. Click on a list.

**Atom Version**: 1.1.0
**System**: Microsoft Windows 10 Pro
**Thrown From**: [imdone-atom](https://github.com/imdone/imdone-atom) package, v1.1.53


### Stack Trace

Uncaught TypeError: Cannot read property 'lists' of undefined

```
At C:\Users\Jeremy\.atom\packages\imdone-atom\node_modules\imdone-core\lib\repository.js:298

TypeError: Cannot read property 'lists' of undefined
  at Repository.getLists (C:\Users\Jeremy\.atom\packages\imdone-atom\node_modules\imdone-core\lib\repository.js:298:26)
  at MenuView.module.exports.MenuView.updateMenu (C:\Users\Jeremy\.atom\packages\imdone-atom\lib\menu-view.coffee:78:18)
  at Repository.<anonymous> (C:\Users\Jeremy\.atom\packages\imdone-atom\lib\menu-view.coffee:66:8)
  at emitOne (events.js:82:20)
  at Repository.emit (events.js:169:7)
  at fn (C:\Users\Jeremy\.atom\packages\imdone-atom\node_modules\imdone-core\lib\repository.js:726:20)
  at FSReqWrap.oncomplete (fs.js:82:15)

```

### Commands

```
     -7:09.5.0 core:move-left (atom-text-editor.editor.is-focused)
     -7:07.8.0 core:save (atom-text-editor.editor.is-focused)
     -7:05.2.0 imdone-atom:tasks (span.name.icon.icon-repo)
     -6:58.6.0 core:backspace (atom-text-editor.editor.is-focused)
     -6:58.1.0 core:save (atom-text-editor.editor.is-focused)
  4x -6:28.8.0 core:backspace (atom-text-editor.editor.is-focused)
     -6:27.2.0 core:save (atom-text-editor.editor.is-focused)
  5x -6:02.0 core:move-right (atom-text-editor.editor.is-focused)
     -6:00.4.0 core:save (atom-text-editor.editor.is-focused)
  3x -5:54.4.0 imdone-atom:tasks (div.header.list-item)
```

### Config

```json
{
  "core": {
    "audioBeep": false
  },
  "imdone-atom": {}
}
```

### Installed Packages

```coffee
# User
imdone-atom, v1.1.53
language-powershell, v2.1.0
language-vbscript, v0.6.1
minimap, v4.15.2
pigments, v0.18.1

# Dev
No dev packages
```

**Comment by piascikj** [comment]
@jeremytwfortune Can you reproduce it? Does it always happen when you click on a list?

**Comment by jeremytwfortune** [comment]
@piascikj, yes, it always happens when clicking on a list.

**Comment by piascikj** [comment]
@jeremytwfortune I just made an update yesterday.  Can you give it a try?

**Comment by jeremytwfortune** [comment]
Needed to restart Atom after the updated, but yes, that looks like it did it.

**Comment by piascikj** [comment]
sweet!  Thanks for checking

On Wed, Nov 11, 2015 at 10:16 AM, Jeremy Fortune <notifications@github.com>
wrote:

> Needed to restart Atom after the updated, but yes, that looks like it did
> it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/imdone/imdone-atom/issues/16#issuecomment-155831982>.
>



-- 
*Jesse Pia**ś**cik*
Founder @imdoneIO <https://twitter.com/imdoneIO> | imdone.io
about.me/jesse.piascik
Expert mentor at Codementor.io
www.codementor.io/codewrangler
