### ISSUE TITLE
Uncaught TypeError: Cannot read property 'tokenfield' of undefined

### ISSUE THREAD

**Issue by bwbarron** [imdone/imdone-atom#172]
1. Load a project
2. Run imdone to view tasks

I just installed this package and tried to run it in my project for the first time and got this error.

**Atom Version**: 1.11.2
**Electron Version**: 0.37.8
**System**: Mac OS X 10.11.6
**Thrown From**: [imdone-atom](https://github.com/imdone/imdone-atom) package, v2.0.9

### Stack Trace

Uncaught TypeError: Cannot read property 'tokenfield' of undefined

```
At /Users/brandonb/.atom/packages/imdone-atom/node_modules/bootstrap-tokenfield/dist/bootstrap-tokenfield.js:976

TypeError: Cannot read property 'tokenfield' of undefined
    at /Users/brandonb/.atom/packages/imdone-atom/node_modules/bootstrap-tokenfield/dist/bootstrap-tokenfield.js:976:17
    at _self (/Users/brandonb/.atom/packages/imdone-atom/node_modules/bootstrap-tokenfield/dist/bootstrap-tokenfield.js:19:7)
    at Object.<anonymous> (/Users/brandonb/.atom/packages/imdone-atom/node_modules/bootstrap-tokenfield/dist/bootstrap-tokenfield.js:30:2)
    at Module._compile (/Users/brandonb/Downloads/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Users/brandonb/Downloads/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (/Users/brandonb/Downloads/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/brandonb/.atom/packages/imdone-atom/lib/views/project-settings-view.coffee:9:1)
    at Object.<anonymous> (/Users/brandonb/.atom/packages/imdone-atom/lib/views/project-settings-view.coffee:1:1)
    at Module._compile (/Users/brandonb/Downloads/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/Users/brandonb/Downloads/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (/Users/brandonb/Downloads/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/brandonb/.atom/packages/imdone-atom/lib/views/share-tasks-view.coffee:10:23)
    at Object.<anonymous> (/Users/brandonb/.atom/packages/imdone-atom/lib/views/share-tasks-view.coffee:1:1)
    at Module._compile (/Users/brandonb/Downloads/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/Users/brandonb/Downloads/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (/Users/brandonb/Downloads/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Function.module.exports.BottomView.content (/Users/brandonb/.atom/packages/imdone-atom/lib/views/bottom-view.coffee:14:22)
    at Function.<anonymous> (/Users/brandonb/.atom/packages/imdone-atom/node_modules/space-pen/lib/space-pen.js:156:31)
    at Function.View.buildHtml (/Users/brandonb/.atom/packages/imdone-atom/node_modules/space-pen/lib/space-pen.js:123:10)
    at BottomView.View [as constructor] (/Users/brandonb/.atom/packages/imdone-atom/node_modules/space-pen/lib/space-pen.js:155:33)
    at new BottomView (/Users/brandonb/.atom/packages/imdone-atom/lib/views/bottom-view.coffee:8:5)
    at Object.content (/Users/brandonb/.atom/packages/imdone-atom/lib/views/imdone-atom-view.coffee:105:40)
    at Builder.tag (/Users/brandonb/.atom/packages/imdone-atom/node_modules/space-pen/lib/space-pen.js:281:19)
    at Function.View.(anonymous function) [as div] (/Users/brandonb/.atom/packages/imdone-atom/node_modules/space-pen/lib/space-pen.js:83:49)
    at Object.content (/Users/brandonb/.atom/packages/imdone-atom/lib/views/imdone-atom-view.coffee:104:12)
    at Builder.tag (/Users/brandonb/.atom/packages/imdone-atom/node_modules/space-pen/lib/space-pen.js:281:19)
    at Function.View.(anonymous function) [as div] (/Users/brandonb/.atom/packages/imdone-atom/node_modules/space-pen/lib/space-pen.js:83:49)
```

### Commands

```
     -5:27.7.0 application:open (atom-text-editor.editor.is-focused)
     -5:02.2.0 core:save (atom-text-editor.editor.is-focused.hyperclick)
     -5:02.1.0 intentions:highlight (atom-text-editor.editor.is-focused)
     -5:02.1.0 imdone-atom:tasks (atom-text-editor.editor.is-focused)
     -3:11.6.0 settings-view:open (atom-text-editor.editor.is-focused.hyperclick)
     -1:27.2.0 tree-view:add-file (span.name.icon.icon-repo)
     -1:21.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:32.8.0 core:save (atom-text-editor.editor.is-focused)
     -0:29.6.0 intentions:highlight (atom-text-editor.editor.hyperclick.is-focused)
     -0:29.3.0 imdone-atom:tasks (atom-text-editor.editor.hyperclick.is-focused)
     -0:18.4.0 tree-view:remove (span.name.icon.icon-file-text)
     -0:00.2.0 intentions:highlight (atom-text-editor.editor.is-focused)
     -0:00.0 imdone-atom:tasks (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "telemetryConsent": "limited"
  }
}
```

### Installed Packages

```coffee
# User
auto-detect-indentation, v1.3.0 (active)
browser-plus, v0.0.76 (active)
color-picker, v2.2.2 (active)
Ensime, v0.39.0 (active)
file-icons, v1.7.23 (active)
hyperclick, v0.0.39 (active)
imdone-atom, v2.0.9 (active)
intentions, v1.1.2 (active)
language-scala, v1.1.7 (active)
linter, v1.11.18 (active)
minimap, v4.25.6 (active)
minimap-autohide, v0.10.1 (active)
todo-show, v1.7.0 (inactive)

# Dev
No dev packages
```

**Comment by piascikj** [comment]
:+1:  Fixed in 2.0.10.  Thanks for the heads up! :beers:
