### ISSUE TITLE
Throws Uncaught Error: Cannot find module './stream-api'

### ISSUE THREAD

**Issue by alexkiura** [imdone/imdone-atom#173]
The error `Uncaught Error: Cannot find module './stream-api'` is thrown when I open the imdone task-board in version2.0.13.

**Comment by piascikj** [comment]
Looks like there might have been a problem when you installed.  This error is coming from a dependency of imdone-atom.  Try uninstalling the package and installing again.

**Comment by alexkiura** [comment]
Reinstalled the package and the error is no more. Thanks 👍🏽

**Comment by k5e** [comment]
Atom 1.11.2; Ubuntu Linux  16.10

I have got the same error:
```
Error: Cannot find module './stream-api'
    at Module._resolveFilename (module.js:339:15)
    at Function.Module._resolveFilename (/usr/share/atom/resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at readdir (/home/username/.atom/packages/imdone-atom/node_modules/imdone-core/node_modules/chokidar/node_modules/readdirp/readdirp.js:52:25)
    at FSWatcher.<anonymous> (/home/username/.atom/packages/imdone-atom/node_modules/imdone-core/node_modules/chokidar/lib/nodefs-handler.js:355:5)
    at FSWatcher.NodeFsHandler._handleDir (/home/username/.atom/packages/imdone-atom/node_modules/imdone-core/node_modules/chokidar/lib/nodefs-handler.js:406:18)
    at FSWatcher.<anonymous> (/home/username/.atom/packages/imdone-atom/node_modules/imdone-core/node_modules/chokidar/lib/nodefs-handler.js:455:19)
    at FSWatcher.<anonymous> (/home/username/.atom/packages/imdone-atom/node_modules/imdone-core/node_modules/chokidar/lib/nodefs-handler.js:460:16)
    at FSReqWrap.oncomplete (fs.js:82:15)
```
Uninstalling and reinstalling of the package did not help. The stack trace is from after the reinstall.
