### ISSUE TITLE
Failed to load the imdone-atom package

### ISSUE THREAD

**Issue by CodingAnarchy** [imdone/imdone-atom#18]
[Enter steps to reproduce below:]

1. Failed upon Atom startup

**Atom Version**: 1.0.7
**System**: Mac OS X 10.10.5
**Thrown From**: [imdone-atom](https://github.com/imdone/imdone-atom) package, v1.1.19

### Stack Trace

Failed to load the imdone-atom package

```
At Cannot find module 'space-pen'

Error: Cannot find module 'space-pen'
    at Module._resolveFilename (module.js:328:15)
    at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:270:25)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at Object.<anonymous> (/Users/ultron/.atom/packages/imdone-atom/node_modules/atom-space-pen-views/lib/main.js:4:10)
    at Object.<anonymous> (/Users/ultron/.atom/packages/imdone-atom/node_modules/atom-space-pen-views/lib/main.js:22:4)
    at Module._compile (module.js:452:26)
    at Object.loadFile [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/babel.js:163:21)
    at Module.load (module.js:347:32)
```

### Commands

```
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
color-picker, v2.0.11
file-icons, v1.6.3
imdone-atom, v1.1.19
language-rust, v0.4.4
linter, v1.3.4
linter-golinter, v1.0.0
linter-rust, v0.2.7
minimap, v4.12.3
pigments, v0.11.0
travis-ci-status, v0.16.0

# Dev
No dev packages
```

**Comment by piascikj** [comment]
Looks like you had an issue with the install.  One of the dependencies of space-pen-views is missing.  Try to uninstall and then install again

**Comment by CodingAnarchy** [comment]
Ok, it looks like reinstalling the package worked.  Just to note, it did work before I updated to 1.0.7, then stopped working with the new version.  Don't know what happened there.

Thanks.  I'll go ahead and close this now that it is working.

**Comment by nesukun** [comment]
I know this issue is resolved but just so you know this failed upgrade is happening to more people. A couple of colleagues and me have experienced this, reinstalling worked tho.

**Comment by piascikj** [comment]
@nesukun Is it the same cause for everyone?
