### ISSUE TITLE
 Cannot read property 'accountName' of undefined

### ISSUE THREAD

**Issue by AkashTripathy** [imdone/imdone-atom#180]
1. The Error Popup comes whenever I press alt+t to see the tasks 

**Atom Version**: 1.12.4
**Electron Version**: 1.3.9
**System**: Microsoft Windows 10 Pro
**Thrown From**: [imdone-atom](https://github.com/imdone/imdone-atom) package, v2.0.17

### Stack Trace

Uncaught TypeError: Cannot read property 'accountName' of undefined

```
At C:\Users\Akash\.atom\packages\imdone-atom\lib\plugins\plugin.coffee:49

TypeError: Cannot read property 'accountName' of undefined
    at ConnectorPlugin.module.exports.ConnectorPlugin.addMetaKeyConfig (file:///C:/Users/Akash/.atom/packages/imdone-atom/lib/plugins/plugin.coffee:49:53)
    at new ConnectorPlugin (file:///C:/Users/Akash/.atom/packages/imdone-atom/lib/plugins/plugin.coffee:20:6)
    at file:///C:/Users/Akash/.atom/packages/imdone-atom/lib/views/imdone-atom-view.coffee:314:22
    at file:///C:/Users/Akash/.atom/packages/imdone-atom/lib/services/connector-manager.coffee:45:7
    at ConnectorManager.module.exports.ConnectorManager.getProducts (file:///C:/Users/Akash/.atom/packages/imdone-atom/lib/services/connector-manager.coffee:36:14)
    at ConnectorManager.module.exports.ConnectorManager.getProduct (file:///C:/Users/Akash/.atom/packages/imdone-atom/lib/services/connector-manager.coffee:44:6)
    at Repository.repo.getProduct (file:///C:/Users/Akash/.atom/packages/imdone-atom/lib/services/imdoneio-store.coffee:286:56)
    at ImdoneAtomView.module.exports.ImdoneAtomView.addPlugin (file:///C:/Users/Akash/.atom/packages/imdone-atom/lib/views/imdone-atom-view.coffee:308:17)
    at ImdoneAtomView.module.exports.ImdoneAtomView.addPluginByProvider (file:///C:/Users/Akash/.atom/packages/imdone-atom/lib/views/imdone-atom-view.coffee:325:6)
    at file:///C:/Users/Akash/.atom/packages/imdone-atom/lib/views/imdone-atom-view.coffee:266:54
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\Akash\AppData\Local\atom\app-1.12.4\resources\app.asar\node_modules\event-kit\lib\emitter.js:25:14)
    at PluginViewInterface.module.exports.Emitter.emit (C:\Users\Akash\AppData\Local\atom\app-1.12.4\resources\app.asar\node_modules\event-kit\lib\emitter.js:129:28)
    at Repository.<anonymous> (file:///C:/Users/Akash/.atom/packages/imdone-atom/lib/views/imdone-atom-view.coffee:122:25)
    at emitOne (events.js:96:13)
    at Repository.emit (events.js:188:7)
    at file:///C:/Users/Akash/.atom/packages/imdone-atom/lib/services/imdoneio-store.coffee:279:12
    at ConnectorManager.module.exports.ConnectorManager.getProducts (file:///C:/Users/Akash/.atom/packages/imdone-atom/lib/services/connector-manager.coffee:36:14)
    at Repository.repo.initProducts (file:///C:/Users/Akash/.atom/packages/imdone-atom/lib/services/imdoneio-store.coffee:277:22)
    at ImdoneAtomView.module.exports.ImdoneAtomView.initImdone (file:///C:/Users/Akash/.atom/packages/imdone-atom/lib/views/imdone-atom-view.coffee:374:19)
    at file:///C:/Users/Akash/.atom/packages/imdone-atom/lib/views/imdone-atom-view.coffee:61:13
    at C:\Users\Akash\.atom\packages\imdone-atom\node_modules\imdone-core\lib\mixins\repo-fs-store.js:257:9
    at C:\Users\Akash\.atom\packages\imdone-atom\node_modules\async\lib\async.js:52:16
    at replenish (C:\Users\Akash\.atom\packages\imdone-atom\node_modules\async\lib\async.js:306:28)
    at C:\Users\Akash\.atom\packages\imdone-atom\node_modules\async\lib\async.js:326:29
    at C:\Users\Akash\.atom\packages\imdone-atom\node_modules\async\lib\async.js:44:16
    at C:\Users\Akash\.atom\packages\imdone-atom\node_modules\imdone-core\lib\mixins\repo-fs-store.js:253:11
    at C:\Users\Akash\.atom\packages\imdone-atom\node_modules\imdone-core\lib\mixins\repo-fs-store.js:105:51
    at FSReqWrap.oncomplete (fs.js:123:15)
```

### Commands

```
 39x -3:44.1.0 core:backspace (atom-text-editor.editor.is-focused)
     -3:35.3.0 core:save (atom-text-editor.editor.is-focused)
     -3:28.2.0 linter:next-error (atom-workspace.workspace.scrollbars-visible-always.panel-shadows.panel-contrast.use-animations.theme-flatwhite-syntax.theme-atom-material-ui.seti-ui-no-icons.paint-cursor.compact-tab-bar.tinted-tab-bar.has-custom-icons)
     -3:22.7.0 editor:newline (atom-text-editor.editor.is-focused)
     -3:22.2.0 core:move-up (atom-text-editor.editor.is-focused)
     -3:21.4.0 core:paste (atom-text-editor.editor.is-focused.hyperclick)
     -3:16 core:backspace (atom-text-editor.editor.is-focused)
 13x -3:14.3.0 core:move-left (atom-text-editor.editor.is-focused)
  2x -3:00.6.0 core:backspace (atom-text-editor.editor.is-focused)
     -2:59.1.0 core:save (atom-text-editor.editor.is-focused.autocomplete-active)
     -2:50.3.0 editor:newline (atom-text-editor.editor.is-focused)
     -2:49.5.0 core:paste (atom-text-editor.editor.is-focused)
  4x -2:48.6.0 core:move-left (atom-text-editor.editor.is-focused)
 39x -2:47.7.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -2:42.3.0 core:save (atom-text-editor.editor.is-focused)
     -0:15.1.0 imdone-atom:tasks (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true,
    "ignoredNames": [
      ".git",
      ".hg",
      ".svn",
      ".DS_Store",
      "._*",
      "Thumbs.db",
      ".gitignore",
      ".gitattributes"
    ],
    "projectHome": "E:\\Study",
    "telemetryConsent": "limited",
    "themes": [
      "atom-material-ui",
      "flatwhite-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
ariake-dark-syntax, v0.0.5 (inactive)
atom-beautify, v0.29.13 (active)
atom-material-syntax, v0.4.6 (inactive)
atom-material-syntax-light, v0.4.5 (inactive)
atom-material-ui, v1.3.6 (active)
atom-runner, v2.7.1 (active)
autocomplete-python, v1.8.12 (active)
blessed-dark-syntax, v0.3.0 (inactive)
file-icons, v1.7.25 (active)
flatwhite-syntax, v0.8.0 (active)
fonts, v1.7.0 (active)
git-plus, v5.25.3 (active)
github-atom-dark-syntax, v0.2.0 (inactive)
github-atom-light-syntax, v0.2.0 (inactive)
hyperclick, v0.0.39 (active)
imdone-atom, v2.0.17 (active)
linter, v1.11.18 (active)
linter-pylama, v0.8.7 (active)
nord-atom-syntax, v0.3.0 (inactive)
nord-atom-ui, v0.8.0 (inactive)
python-indent, v1.0.0 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.45.0 (inactive)
base16-tomorrow-dark-theme, v1.3.0 (inactive)
base16-tomorrow-light-theme, v1.3.0 (inactive)
one-dark-ui, v1.6.2 (inactive)
one-light-ui, v1.6.2 (inactive)
one-dark-syntax, v1.5.0 (inactive)
one-light-syntax, v1.5.0 (inactive)
solarized-dark-syntax, v1.0.5 (inactive)
solarized-light-syntax, v1.0.5 (inactive)
about, v1.7.0 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.13.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.4 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.2 (active)
command-palette, v0.39.0 (active)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.202.2 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.158.8 (active)
metrics, v1.1.2 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.1 (inactive)
settings-view, v0.243.1 (active)
snippets, v1.0.4 (active)
spell-check, v0.68.4 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.2 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.0 (active)
timecop, v0.33.2 (active)
tree-view, v0.210.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.35.0 (active)
wrap-guide, v0.38.2 (active)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (active)
language-coffee-script, v0.48.0 (active)
language-csharp, v0.13.0 (active)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.46.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.37.0 (active)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)

# Dev
No dev packages
```

**Comment by piascikj** [comment]
Looks like a bug.  I just published a fix for this.  Should be working now.
