### ISSUE TITLE
Uncaught TypeError: Cannot read property 'toString' of undefined

### ISSUE THREAD

**Issue by jm-welch** [imdone/imdone-atom#184]
[Enter steps to reproduce below:]

1. Set up imdone account
2. Log in in a project with existing issues
3. Configure the github URL for the repo in imdone settings
4. Click the octocat icon for an existing issue
5. Click "New Issue"

**Atom Version**: 1.12.6
**Electron Version**: 1.3.9
**System**: Mac OS X 10.11.6
**Thrown From**: [imdone-atom](https://github.com/imdone/imdone-atom) package, v2.0.19

### Stack Trace

Uncaught TypeError: Cannot read property 'toString' of undefined

```
At /Users/jwelch/.atom/packages/imdone-atom/node_modules/imdone-core/lib/task.js:215

TypeError: Cannot read property 'toString' of undefined
    at Task._addMetaData (/Users/jwelch/.atom/packages/imdone-atom/node_modules/imdone-core/lib/task.js:215:12)
    at Task.addMetaData (/Users/jwelch/.atom/packages/imdone-atom/node_modules/imdone-core/lib/task.js:208:10)
    at /Users/jwelch/.atom/packages/imdone-atom/lib/plugins/plugin-view.coffee:101:13
    at /Users/jwelch/.atom/packages/imdone-atom/lib/services/imdoneio-client.coffee:239:14
    at Request.callback (/Users/jwelch/.atom/packages/imdone-atom/node_modules/superagent/lib/node/index.js:631:3)
    at /Users/jwelch/.atom/packages/imdone-atom/node_modules/superagent/lib/node/index.js:795:18
    at IncomingMessage.<anonymous> (/Users/jwelch/.atom/packages/imdone-atom/node_modules/superagent/lib/node/parsers/json.js:16:7)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

### Commands

```
     -8:09.9.0 settings-view:install-packages-and-themes (button.btn.btn-success.inline-block-tight)
     -8:03.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -7:09.7.0 core:paste (atom-text-editor#imdone-atom-github.accessToken.editor.mini.is-focused)
     -7:09.0 core:save (atom-text-editor#imdone-atom-github.accessToken.editor.mini.is-focused)
     -0:43.6.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:38.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:38.6.0 imdone-atom:tasks (atom-text-editor.editor)
     -0:14.6.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:13.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:13.3.0 imdone-atom:tasks (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "openEmptyEditorOnStart": false,
    "telemetryConsent": "no"
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.29.13 (active)
atom-jinja2, v0.5.0 (active)
css-snippets, v1.1.0 (active)
django-templates, v0.5.0 (active)
html-id-class-snippets, v1.4.1 (active)
imdone-atom, v2.0.19 (active)
language-ansible, v0.1.11 (active)
language-nagios, v0.2.0 (active)
line-ending-converter, v1.3.2 (active)
minimap, v4.25.6 (active)
pigments, v0.37.0 (active)
pretty-json, v1.6.1 (active)
project-plus, v0.9.0 (active)
terminal-plus, v0.14.5 (active)
xml-formatter, v0.10.0 (inactive)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.45.0 (inactive)
base16-tomorrow-dark-theme, v1.3.0 (inactive)
base16-tomorrow-light-theme, v1.3.0 (inactive)
one-dark-ui, v1.6.2 (active)
one-light-ui, v1.6.2 (inactive)
one-dark-syntax, v1.5.0 (active)
one-light-syntax, v1.5.0 (inactive)
solarized-dark-syntax, v1.0.5 (inactive)
solarized-light-syntax, v1.0.5 (inactive)
about, v1.7.0 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.13.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.4 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.2 (active)
command-palette, v0.39.0 (active)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.202.2 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.158.8 (active)
metrics, v1.1.2 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.1 (inactive)
settings-view, v0.243.1 (active)
snippets, v1.0.4 (active)
spell-check, v0.68.4 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.2 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.0 (active)
timecop, v0.33.2 (active)
tree-view, v0.210.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.35.0 (active)
wrap-guide, v0.38.2 (active)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (active)
language-coffee-script, v0.48.0 (active)
language-csharp, v0.13.0 (active)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.47.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.37.0 (active)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)

# Dev
No dev packages
```

**Comment by plashal** [comment]
Looks like I got the same error.

> Win10Pro x64 v.1607
> Atom 1.14.4

```
- Uncaught TypeError: Cannot read property 'toString' of undefined

- C:\Users\****\.atom\packages\imdone-atom\node_modules\imdone-core\lib\task.js:215

- TypeError: Cannot read property 'toString' of undefined
    at Task._addMetaData (C:\Users\****\.atom\packages\imdone-atom\node_modules\imdone-core\lib\task.js:215:12)
    at Task.addMetaData (C:\Users\****\.atom\packages\imdone-atom\node_modules\imdone-core\lib\task.js:208:10)
    at file:///C:/Users/****/.atom/packages/imdone-atom/lib/plugins/plugin-view.coffee:102:13
    at file:///C:/Users/****/.atom/packages/imdone-atom/lib/services/imdoneio-client.coffee:239:14
    at Request.callback (C:\Users\****\.atom\packages\imdone-atom\node_modules\superagent\lib\node\index.js:631:3)
    at C:\Users\****\.atom\packages\imdone-atom\node_modules\superagent\lib\node\index.js:795:18
    at IncomingMessage.<anonymous> (C:\Users\****\.atom\packages\imdone-atom\node_modules\superagent\lib\node\parsers\json.js:16:7)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by piascikj** [comment]
Is this still an issue?

**Comment by mobilekbs** [comment]
Did you solve it? If so, kindly share the solution for the same. Thank you
