### ISSUE TITLE
Uncaught Error: Cannot find module 'debug/browser'

### ISSUE THREAD

**Issue by marcus-crane** [imdone/imdone-atom#187]
Upon first installing imdone-atom and hitting alt-t, I'm presented with the following stack trace:

```
Error: Cannot find module 'debug/browser'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/Sentry/.atom/packages/imdone-atom/lib/services/connector-manager.coffee:4:7)
    at Object.<anonymous> (/Users/Sentry/.atom/packages/imdone-atom/lib/services/connector-manager.coffee:1:1)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:201:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at module.exports (/Users/Sentry/.atom/packages/imdone-atom/lib/services/imdoneio-store.coffee:2:22)
    at Object.getRepo (/Users/Sentry/.atom/packages/imdone-atom/lib/services/imdone-helper.coffee:15:23)
    at Object.createImdoneAtomView (/Users/Sentry/.atom/packages/imdone-atom/lib/imdone-atom.coffee:192:25)
    at Object.viewForUri (/Users/Sentry/.atom/packages/imdone-atom/lib/imdone-atom.coffee:187:6)
    at /Users/Sentry/.atom/packages/imdone-atom/lib/imdone-atom.coffee:123:8
    at Workspace.module.exports.Workspace.openURIInPane (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:501:22)
    at Workspace.module.exports.Workspace.open (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:436:19)
    at Object.tasks (/Users/Sentry/.atom/packages/imdone-atom/lib/imdone-atom.coffee:140:20)
    at atom-workspace.<anonymous> (/Users/Sentry/.atom/packages/imdone-atom/lib/imdone-atom.coffee:109:8)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:259:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:59
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:587:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:382:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:106:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:59)
```

The "Create issue" link that it generates also triggers a `414 Request-URI Too Large` with Github. The link in question that causes it for me is

```
https://github.com/imdone/imdone-atom/issues/new?title=Uncaught%20Error:%20Cannot%20find%20module%20%27debug/browser%27&body=%5BEnter%20steps%20to%20reproduce%20below:%5D%0A%0A1.%20...%0A2.%20...%0A%0A**Atom%20Version**:%201.12.7%0A**Electron%20Version**:%201.3.13%0A**System**:%20Mac%20OS%20X%2010.12.2%0A**Thrown%20From**:%20%5Bimdone-atom%5D(https://github.com/imdone/imdone-atom)%20package,%20v2.0.19%0A%0A%0A%23%23%23%20Stack%20Trace%0A%0AUncaught%20Error:%20Cannot%20find%20module%20%27debug/browser%27%0A%0A%60%60%60%0AAt%20module.js:457%0A%0AError:%20Cannot%20find%20module%20%27debug/browser%27%0A%20%20%20%20at%20Module._resolveFilename%20(module.js:455:15)%0A%20%20%20%20at%20Module._resolveFilename%20(/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)%0A%20%20%20%20at%20Function.Module._resolveFilename%20(/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)%0A%20%20%20%20at%20Function.Module._load%20(module.js:403:25)%0A%20%20%20%20at%20Module.require%20(module.js:483:17)%0A%20%20%20%20at%20require%20(/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)%0A%20%20%20%20at%20Object.%3Canonymous%3E%20(/Users/Sentry/.atom/packages/imdone-atom/lib/services/connector-manager.coffee:4:7)%0A%20%20%20%20at%20Object.%3Canonymous%3E%20(/Users/Sentry/.atom/packages/imdone-atom/lib/services/connector-manager.coffee:1:1)%0A%20%20%20%20at%20Module._compile%20(/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)%0A%20%20%20%20at%20Object.value%20%5Bas%20.coffee%5D%20(/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:201:21)%0A%20%20%20%20at%20Module.load%20(module.js:473:32)%0A%20%20%20%20at%20tryModuleLoad%20(module.js:432:12)%0A%20%20%20%20at%20Function.Module._load%20(module.js:424:3)%0A%20%20%20%20at%20Module.require%20(module.js:483:17)%0A%20%20%20%20at%20require%20(/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)%0A%20%20%20%20at%20module.exports%20(/Users/Sentry/.atom/packages/imdone-atom/lib/services/imdoneio-store.coffee:2:22)%0A%20%20%20%20at%20Object.getRepo%20(/Users/Sentry/.atom/packages/imdone-atom/lib/services/imdone-helper.coffee:15:23)%0A%20%20%20%20at%20Object.createImdoneAtomView%20(/Users/Sentry/.atom/packages/imdone-atom/lib/imdone-atom.coffee:192:25)%0A%20%20%20%20at%20Object.viewForUri%20(/Users/Sentry/.atom/packages/imdone-atom/lib/imdone-atom.coffee:187:6)%0A%20%20%20%20at%20/Users/Sentry/.atom/packages/imdone-atom/lib/imdone-atom.coffee:123:8%0A%20%20%20%20at%20Workspace.module.exports.Workspace.openURIInPane%20(/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:501:22)%0A%20%20%20%20at%20Workspace.module.exports.Workspace.open%20(/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:436:19)%0A%20%20%20%20at%20Object.tasks%20(/Users/Sentry/.atom/packages/imdone-atom/lib/imdone-atom.coffee:140:20)%0A%20%20%20%20at%20atom-workspace.%3Canonymous%3E%20(/Users/Sentry/.atom/packages/imdone-atom/lib/imdone-atom.coffee:109:8)%0A%20%20%20%20at%20CommandRegistry.module.exports.CommandRegistry.handleCommandEvent%20(/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:259:29)%0A%20%20%20%20at%20/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:59%0A%20%20%20%20at%20KeymapManager.module.exports.KeymapManager.dispatchCommandEvent%20(/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:587:16)%0A%20%20%20%20at%20KeymapManager.module.exports.KeymapManager.handleKeyboardEvent%20(/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:382:22)%0A%20%20%20%20at%20WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent%20(/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:106:36)%0A%20%20%20%20at%20HTMLDocument.%3Canonymous%3E%20(/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:59)%0A%60%60%60%0A%0A%23%23%23%20Commands%0A%0A%60%60%60%0A%20%202x%20-8:56.4.0%20window:decrease-font-size%20(atom-pane.pane.active)%0A%20%20%20%20%20-8:43.2.0%20application:add-project-folder%20(ul.list-inline.tab-bar.inset-panel)%0A%20%205x%20-8:29.7.0%20core:confirm%20(atom-text-editor.editor.mini.is-focused)%0A%20%209x%20-6:11.1.0%20core:backspace%20(atom-text-editor%23atom-clock.dateFormat.editor.mini.is-focused)%0A%20%205x%20-6:00.1.0%20core:move-left%20(atom-text-editor%23atom-clock.dateFormat.editor.mini.is-focused)%0A%20%205x%20-5:58.2.0%20core:move-right%20(atom-text-editor%23atom-clock.dateFormat.editor.mini.is-focused)%0A%20%203x%20-5:56.7.0%20core:backspace%20(atom-text-editor%23atom-clock.dateFormat.editor.mini.is-focused)%0A%20%206x%20-5:49.7.0%20core:move-left%20(atom-text-editor%23atom-clock.dateFormat.editor.mini.is-focused)%0A%20%204x%20-5:33.8.0%20core:backspace%20(atom-text-editor%23atom-clock.dateFormat.editor.mini.is-focused)%0A%20%202x%20-4:51.7.0%20imdone-atom:tasks%20(atom-text-editor%23imdone-atom.todaysJournal.dateFormat.editor.mini.is-focused)%0A%20%20%20%20%20-2:34.9.0%20core:select-all%20(atom-text-editor.editor.mini.is-focused)%0A%20%204x%20-2:34.1.0%20core:backspace%20(atom-text-editor.editor.mini.is-focused)%0A%20%20%20%20%20-2:32.1.0%20core:confirm%20(atom-text-editor.editor.mini.is-focused)%0A%20%20%20%20%20-0:00.0%20imdone-atom:tasks%20(div.package-detail.panels-item)%0A%60%60%60%0A%0A%23%23%23%20Config%0A%0A%60%60%60json%0A%7B%0A%20%20%22core%22:%20%7B%0A%20%20%20%20%22telemetryConsent%22:%20%22limited%22%0A%20%20%7D,%0A%20%20%22imdone-atom%22:%20%7B%0A%20%20%20%20%22todaysJournal%22:%20%7B%0A%20%20%20%20%20%20%22dateFormat%22:%20%22DD-MM-YYYY%22%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A%60%60%60%0A%0A%23%23%23%20Installed%20Packages%0A%0A%60%60%60coffee%0A%23%20User%0Aatom-clock,%20v0.0.8%20(active)%0Aimdone-atom,%20v2.0.19%20(active)%0Aatom-dark-syntax,%20v0.27.0%20(inactive)%0Aatom-dark-ui,%20v0.52.0%20(inactive)%0Aatom-light-syntax,%20v0.28.0%20(inactive)%0Aatom-light-ui,%20v0.45.0%20(inactive)%0Abase16-tomorrow-dark-theme,%20v1.3.0%20(inactive)%0Abase16-tomorrow-light-theme,%20v1.3.0%20(inactive)%0Aone-dark-ui,%20v1.6.2%20(active)%0Aone-light-ui,%20v1.6.2%20(inactive)%0Aone-dark-syntax,%20v1.5.0%20(active)%0Aone-light-syntax,%20v1.5.0%20(inactive)%0Asolarized-dark-syntax,%20v1.0.5%20(inactive)%0Asolarized-light-syntax,%20v1.0.5%20(inactive)%0Aabout,%20v1.7.0%20(active)%0Aarchive-view,%20v0.62.0%20(active)%0Aautocomplete-atom-api,%20v0.10.0%20(active)%0Aautocomplete-css,%20v0.13.1%20(active)%0Aautocomplete-html,%20v0.7.2%20(active)%0Aautocomplete-plus,%20v2.31.4%20(active)%0Aautocomplete-snippets,%20v1.11.0%20(active)%0Aautoflow,%20v0.27.0%20(inactive)%0Aautosave,%20v0.23.1%20(active)%0Abackground-tips,%20v0.26.1%20(active)%0Abookmarks,%20v0.42.0%20(active)%0Abracket-matcher,%20v0.82.2%20(active)%0Acommand-palette,%20v0.39.0%20(inactive)%0Adeprecation-cop,%20v0.54.1%20(active)%0Adev-live-reload,%20v0.47.0%20(active)%0Aencoding-selector,%20v0.22.0%20(active)%0Aexception-reporting,%20v0.40.0%20(active)%0Afind-and-replace,%20v0.202.2%20(inactive)%0Afuzzy-finder,%20v1.4.0%20(active)%0Agit-diff,%20v1.1.0%20(active)%0Ago-to-line,%20v0.31.0%20(inactive)%0Agrammar-selector,%20v0.48.2%20(active)%0Aimage-view,%20v0.60.0%20(active)%0Aincompatible-packages,%20v0.26.1%20(active)%0Akeybinding-resolver,%20v0.35.0%20(active)%0Aline-ending-selector,%20v0.5.0%20(active)%0Alink,%20v0.31.2%20(inactive)%0Amarkdown-preview,%20v0.158.8%20(active)%0Ametrics,%20v1.1.2%20(active)%0Anotifications,%20v0.65.1%20(active)%0Aopen-on-github,%20v1.2.1%20(inactive)%0Apackage-generator,%20v1.0.1%20(inactive)%0Asettings-view,%20v0.243.1%20(active)%0Asnippets,%20v1.0.4%20(active)%0Aspell-check,%20v0.68.4%20(active)%0Astatus-bar,%20v1.4.1%20(active)%0Astyleguide,%20v0.47.2%20(active)%0Asymbols-view,%20v0.113.1%20(inactive)%0Atabs,%20v0.103.0%20(active)%0Atimecop,%20v0.33.2%20(active)%0Atree-view,%20v0.210.0%20(active)%0Aupdate-package-dependencies,%20v0.10.0%20(active)%0Awelcome,%20v0.35.1%20(active)%0Awhitespace,%20v0.35.0%20(active)%0Awrap-guide,%20v0.38.2%20(active)%0Alanguage-c,%20v0.54.0%20(active)%0Alanguage-clojure,%20v0.22.1%20(active)%0Alanguage-coffee-script,%20v0.48.0%20(active)%0Alanguage-csharp,%20v0.13.0%20(active)%0Alanguage-css,%20v0.40.1%20(active)%0Alanguage-gfm,%20v0.88.0%20(active)%0Alanguage-git,%20v0.15.0%20(active)%0Alanguage-go,%20v0.43.0%20(active)%0Alanguage-html,%20v0.47.1%20(active)%0Alanguage-hyperlink,%20v0.16.1%20(active)%0Alanguage-java,%20v0.24.0%20(active)%0Alanguage-javascript,%20v0.122.0%20(active)%0Alanguage-json,%20v0.18.3%20(active)%0Alanguage-less,%20v0.29.6%20(active)%0Alanguage-make,%20v0.22.2%20(active)%0Alanguage-mustache,%20v0.13.0%20(active)%0Alanguage-objective-c,%20v0.15.1%20(active)%0Alanguage-perl,%20v0.37.0%20(active)%0Alanguage-php,%20v0.37.3%20(active)%0Alanguage-property-list,%20v0.8.0%20(active)%0Alanguage-python,%20v0.45.1%20(active)%0Alanguage-ruby,%20v0.70.2%20(active)%0Alanguage-ruby-on-rails,%20v0.25.1%20(active)%0Alanguage-sass,%20v0.57.0%20(active)%0Alanguage-shellscript,%20v0.23.0%20(active)%0Alanguage-source,%20v0.9.0%20(active)%0Alanguage-sql,%20v0.25.0%20(active)%0Alanguage-text,%20v0.7.1%20(active)%0Alanguage-todo,%20v0.29.1%20(active)%0Alanguage-toml,%20v0.18.1%20(active)%0Alanguage-xml,%20v0.34.12%20(active)%0Alanguage-yaml,%20v0.27.1%20(active)%0A%0A%23%20Dev%0ANo%20dev%20packages%0A%60%60%60%0A%0A
```

**Comment by pranshu1992** [comment]
any update on this issue ?

**Comment by sazzer** [comment]
I've just rolled back to 2.0.0 and the problem is still present. Going back to 1.3.31 - the version before - and it's not present, so it's something in the jump to 2.0.0 that's caused it.

**Comment by piascikj** [comment]
I'll have a look today.  Probably a minor fix.

**Comment by marcus-crane** [comment]
Same deal as @sazzer. Installing 1.3.31 works perfectly fine but updating to 2.0.0 and beyond results in the error I mentioned.

**Comment by marcus-crane** [comment]
Thanks @piascikj!
