### ISSUE TITLE
package.coffee:413 Error deactivating package 'imdone-atom' TypeError: Cannot read property 'destroyRepos' of null

### ISSUE THREAD

**Issue by seanbuscay** [imdone/imdone-atom#195]
This error occurs during Atom window reloads.

_System settings are pasted below the error message._

To replicate:

1. Toggle the developer tools window
2. Check the 'Preserve Log' check box
3. (Optional) Clear previous log entries
4. From the View menu item choose Developer -> Reload Window
5. The error should be displayed in the developer tools window

Note: Line 145 in `imdone-atom.coffee` appears to have been modified in the last release with this `mdoneHelper.destroyRepos()`

```
package.coffee:413 Error deactivating package 'imdone-atom' TypeError: Cannot read property 'destroyRepos' of null
    at Object.deactivate (/Users/seanbuscay/.atom/packages/imdone-atom/lib/imdone-atom.coffee:145:17)
    at Package.module.exports.Package.deactivate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:674:20)
    at PackageManager.module.exports.PackageManager.deactivatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:643:12)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:629:19
    at Config.module.exports.Config.transact (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:312:16)
    at PackageManager.module.exports.PackageManager.deactivatePackages (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:623:19)
    at AtomEnvironment.module.exports.AtomEnvironment.unloadEditorWindow (/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:825:21)
    at WindowEventHandler.module.exports.WindowEventHandler.handleWindowBeforeunload (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:212:30)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:59
```

System:

```
apm  1.12.9
npm  3.10.5
node 4.4.5
Atom 1.12.8
imdone-atom 2.1.0
```

**Comment by piascikj** [comment]
Replace this with something meaningful like... "@piascikj started working this issue."

----

DOING: That dang destroy error id:122 gh:195
[**lib/imdone-atom.coffee:146**](https://github.com/imdone/imdone-atom/blob/master/lib/imdone-atom.coffee#L146)

@imdone *comment-bot*. Get TODOBOTs to do your work at [imdone.io](https://imdone.io)

**Comment by piascikj** [comment]
Replace this with something meaningful like... "@piascikj started working this issue."

----

READY: That dang destroy error id:122 gh:195
[**lib/imdone-atom.coffee:146**](https://github.com/imdone/imdone-atom/blob/master/lib/imdone-atom.coffee#L146)

@imdone *comment-bot*. Get TODOBOTs to do your work at [imdone.io](https://imdone.io)

**Comment by piascikj** [comment]
DONE: That dang destroy error id:122 gh:195
      [**lib/imdone-atom.coffee:146**](https://github.com/imdone/imdone-atom/blob/undefined/lib/imdone-atom.coffee#L146)  
@imdone *closer-bot*. Get TODOBOTs to do your work at [imdone.io](https://imdone.io)

**Comment by piascikj** [comment]
@seanbuscay Thanks for reporting this.  It's fixed in the latest release.
