### ISSUE TITLE
Uncaught TypeError: Cannot read property 'accountName' of undefined

### ISSUE THREAD

**Issue by jorenrothman** [imdone/imdone-atom#206]
**Atom Version**: 1.13.0
**System**: Mac OS X 10.12.2
**Thrown From**: [imdone-atom](https://github.com/imdone/imdone-atom) package, v2.1.11

### Stack Trace

Uncaught TypeError: Cannot read property 'accountName' of undefined

```
At /Users/joren/.atom/packages/imdone-atom/lib/plugins/plugin.coffee:49

TypeError: Cannot read property 'accountName' of undefined
    at ConnectorPlugin.module.exports.ConnectorPlugin.issuesUrlBase (/Users/joren/.atom/packages/imdone-atom/lib/plugins/plugin.coffee:49:38)
    at ConnectorPlugin.module.exports.ConnectorPlugin.projectButtons (/Users/joren/.atom/packages/imdone-atom/lib/plugins/plugin.coffee:93:22)
    at MenuView.module.exports.MenuView.addPluginProjectButtons (/Users/joren/.atom/packages/imdone-atom/lib/views/menu-view.coffee:102:45)
    at ImdoneAtomView.module.exports.ImdoneAtomView.addPluginProjectButtons (/Users/joren/.atom/packages/imdone-atom/lib/views/imdone-atom-view.coffee:317:41)
    at ImdoneAtomView.module.exports.ImdoneAtomView.addPluginButtons (/Users/joren/.atom/packages/imdone-atom/lib/views/imdone-atom-view.coffee:298:6)
    at ImdoneAtomView.module.exports.ImdoneAtomView.updateBoard (/Users/joren/.atom/packages/imdone-atom/lib/views/imdone-atom-view.coffee:610:6)
    at ImdoneAtomView.module.exports.ImdoneAtomView.onRepoUpdate (/Users/joren/.atom/packages/imdone-atom/lib/views/imdone-atom-view.coffee:411:6)
    at ImdoneAtomView.module.exports.ImdoneAtomView.initImdone (/Users/joren/.atom/packages/imdone-atom/lib/views/imdone-atom-view.coffee:391:8)
    at /Users/joren/.atom/packages/imdone-atom/lib/views/imdone-atom-view.coffee:64:10
    at /Users/joren/.atom/packages/imdone-atom/node_modules/imdone-core/lib/mixins/repo-fs-store.js:94:11
    at done (/Users/joren/.atom/packages/imdone-atom/node_modules/node-dir/lib/paths.js:27:13)
    at /Users/joren/.atom/packages/imdone-atom/node_modules/node-dir/lib/paths.js:53:37
    at done (/Users/joren/.atom/packages/imdone-atom/node_modules/node-dir/lib/paths.js:25:13)
    at /Users/joren/.atom/packages/imdone-atom/node_modules/node-dir/lib/paths.js:53:37
    at done (/Users/joren/.atom/packages/imdone-atom/node_modules/node-dir/lib/paths.js:25:13)
    at /Users/joren/.atom/packages/imdone-atom/node_modules/node-dir/lib/paths.js:60:33
    at FSReqWrap.oncomplete (fs.js:123:15)
```

### Commands

```
     -9:57 tree-view:toggle (ol.ftptree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -9:46.6.0 tree-view:remove-project-folder (span.name.icon.icon-file-directory)
     -9:46.5.0 remote-ftp:disconnect (atom-workspace.workspace.scrollbars-visible-always.theme-spacegray-atom-dark-syntax.theme-one-dark-ui.find-visible)
     -9:46.5.0 remote-ftp:connect (atom-workspace.workspace.scrollbars-visible-always.theme-spacegray-atom-dark-syntax.theme-one-dark-ui.find-visible)
     -9:16.6.0 imdone-atom:tasks (input.hidden-input)
     -9:09.2.0 core:copy (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
     -8:14.5.0 tree-view:toggle (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -7:49.1.0 find-and-replace:show (input.hidden-input)
  8x -7:47.2.0 core:confirm (input.hidden-input)
  3x -7:31.1.0 core:save (input.hidden-input)
     -2:20.9.0 imdone-atom:tasks (input.hidden-input)
     -2:12.4.0 core:copy (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
     -0:00.1.0 imdone-atom:tasks (input.hidden-input)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "linter-sass-lint",
      "linter-tidy",
      "linter-php",
      "console-panel"
    ],
    "excludeVcsIgnoredPaths": false,
    "telemetryConsent": "limited",
    "themes": [
      "one-dark-ui",
      "spacegray-atom-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-alignment, v0.12.1 (active)
atom-css-unit-converter, v1.1.1 (inactive)
atom-terminal, v0.8.0 (inactive)
code-peek, v1.4.14 (inactive)
console-panel, v0.2.1 (inactive)
dash, v1.7.0 (inactive)
emmet, v2.4.3 (active)
file-icons, v2.0.10 (active)
git-plus, v7.2.0 (active)
github-atom-dark-syntax, v0.3.2 (inactive)
highlight-selected, v0.12.0 (active)
imdone-atom, v2.1.11 (active)
linter, v1.11.21 (active)
linter-jshint, v3.0.2 (active)
linter-scss-lint, v3.0.4 (active)
minimap, v4.26.7 (active)
multi-cursor, v2.1.5 (inactive)
pigments, v0.38.0 (active)
project-manager, v3.3.3 (active)
quick-editor, v0.4.3 (inactive)
Remote-FTP, v0.10.3 (active)
section-comment-snippets, v2.4.1 (active)
snippet-generator, v0.3.2 (inactive)
spacegray-atom-dark-syntax, v1.3.1 (active)
spacegray-dark-neue-ui, v1.7.1 (inactive)
svg-preview, v0.11.0 (active)
sync-settings, v0.8.1 (active)
tasks, v2.6.4 (active)
tool-bar, v1.0.1 (active)
tool-bar-main, v0.0.10 (active)
turbo-javascript, v1.4.0 (inactive)
wordpress-api, v1.2.2 (active)
zentabs, v0.8.8 (active)
atom-dark-syntax, v0.28.0 (inactive)
atom-dark-ui, v0.53.0 (inactive)
atom-light-syntax, v0.29.0 (inactive)
atom-light-ui, v0.46.0 (inactive)
base16-tomorrow-dark-theme, v1.4.0 (inactive)
base16-tomorrow-light-theme, v1.4.0 (inactive)
one-dark-ui, v1.8.2 (active)
one-light-ui, v1.8.2 (inactive)
one-dark-syntax, v1.6.0 (inactive)
one-light-syntax, v1.6.0 (inactive)
solarized-dark-syntax, v1.1.1 (inactive)
solarized-light-syntax, v1.1.1 (inactive)
about, v1.7.2 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.14.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.33.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.29.0 (inactive)
autosave, v0.23.2 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.43.2 (active)
bracket-matcher, v0.85.1 (active)
command-palette, v0.39.1 (active)
deprecation-cop, v0.55.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.204.5 (active)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.2.0 (active)
go-to-line, v0.31.2 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.1 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.159.1 (active)
metrics, v1.1.2 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.2 (inactive)
settings-view, v0.244.0 (active)
snippets, v1.0.4 (active)
spell-check, v0.68.5 (active)
status-bar, v1.6.0 (active)
styleguide, v0.48.0 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.1 (active)
timecop, v0.33.2 (active)
tree-view, v0.211.1 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.35.0 (active)
wrap-guide, v0.39.0 (active)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (active)
language-coffee-script, v0.48.1 (active)
language-csharp, v0.13.0 (active)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.47.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.37.0 (active)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)

# Dev
No dev packages
```

**Comment by jorenrothman** [comment]
Already fixed it just removed my config folder

**Comment by piascikj** [comment]
Haha! Thanks!
