### ISSUE TITLE
Uncaught TypeError: plugin.projectButtons is not a function

### ISSUE THREAD

**Issue by plashal** [imdone/imdone-atom#213]
[Enter steps to reproduce:]

1. right-clicking in the tree view, 
2. don't know if i did anything out the ordinary 

**Atom**: 1.14.2 ia32
**Electron**: 1.3.13
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [imdone-atom](https://github.com/imdone/imdone-atom) package 2.1.18

### Stack Trace

Uncaught TypeError: plugin.projectButtons is not a function

```
At C:\Users\TildeMoose\.atom\packages\imdone-atom\lib\views\menu-view.coffee:103

TypeError: plugin.projectButtons is not a function
    at MenuView.module.exports.MenuView.addPluginProjectButtons (/packages/imdone-atom/lib/views/menu-view.coffee:103:85)
    at ImdoneAtomView.module.exports.ImdoneAtomView.addPluginProjectButtons (/packages/imdone-atom/lib/views/imdone-atom-view.coffee:317:41)
    at ImdoneAtomView.module.exports.ImdoneAtomView.addPluginButtons (/packages/imdone-atom/lib/views/imdone-atom-view.coffee:298:6)
    at /packages/imdone-atom/lib/views/imdone-atom-view.coffee:333:10
    at /packages/imdone-atom/lib/services/connector-manager.coffee:45:7
    at /packages/imdone-atom/lib/services/connector-manager.coffee:41:7
    at /packages/imdone-atom/lib/services/imdoneio-client.coffee:198:7
    at Request.callback (/packages/imdone-atom/node_modules/superagent/lib/node/index.js:619:12)
    at /packages/imdone-atom/node_modules/superagent/lib/node/index.js:795:18
    at /packages/imdone-atom/node_modules/superagent/lib/node/parsers/json.js:16:7)
    at emitNone (events.js:86:13)
    at Stream.emit (events.js:185:7)
    at /packages/imdone-atom/node_modules/superagent/lib/node/utils.js:112:12)
    at emitNone (events.js:91:20)
    at Unzip.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

### Commands

```
     -2:08.5.0 core:move-down (input.hidden-input)
     -2:07.8.0 core:confirm (input.hidden-input)
     -2:07.8.0 bookmarks:clear-bookmarks (input.hidden-input)
     -1:48.2.0 command-palette:toggle (input.hidden-input)
     -1:24.4.0 autocomplete-plus:activate (input.hidden-input)
     -1:21.6.0 command-palette:toggle (input.hidden-input)
     -1:16.7.0 autocomplete-plus:activate (input.hidden-input)
     -1:15.1.0 command-palette:toggle (input.hidden-input)
     -0:58.5.0 status-bar:toggle (input.hidden-input)
     -0:55.7.0 command-palette:toggle (input.hidden-input)
  2x -0:49.5.0 core:backspace (input.hidden-input)
     -0:46.1.0 status-bar:toggle (input.hidden-input)
     -0:39.5.0 linter:next-error (atom-workspace.workspace.scrollbars-visible-always.seti-icons.seti-roboto.seti-animate.theme-seti-syntax.theme-seti-ui)
  2x -0:37 go-to-line:toggle (atom-text-editor.editor)
     -0:29.1.0 tree-view:toggle-focus (ul.list-inline.tab-bar.inset-panel)
     -0:15.8.0 imdone-atom:tasks (span.name.icon.icon-repo)
```

### Non-Core Packages

```
atom-beautify 0.29.17 
atom-monokai 0.10.8 
autoclose-html 0.23.0 
color-picker 2.2.5 
colorblind-wombat-dark-syntax 0.6.0 
file-icons 2.0.15 
git-plus 7.3.0 
highlight-selected 0.12.0 
imdone-atom 2.1.18 
imdone-atom-github 0.1.11 
linter 1.11.23 
linter-csslint 1.3.3 
linter-htmlhint 1.3.1 
linter-jshint 3.0.2 
linter-markdown 3.1.0 
linter-shellcheck 1.4.3 
minimap 4.26.8 
minimap-bookmarks 0.4.2 
minimap-cursorline 0.2.0 
minimap-highlight-selected 4.5.0 
monokai 0.22.0 
pigments 0.39.0 
ramda-syntax 0.12.0 
Remote-FTP 0.10.5 
seti-syntax 1.1.2 
seti-ui 1.6.1 
todo-show 1.10.0 
```

**Comment by rayk** [comment]
[Enter steps to reproduce:]

1. Add List in Imdone
2. ...

**Atom**: 1.14.4 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.3
**Thrown From**: [imdone-atom](https://github.com/imdone/imdone-atom) package 2.1.21


### Stack Trace

Uncaught TypeError: plugin.projectButtons is not a function

```
At /Users/rayk/.atom/packages/imdone-atom/lib/views/menu-view.coffee:103

TypeError: plugin.projectButtons is not a function
    at MenuView.module.exports.MenuView.addPluginProjectButtons (/packages/imdone-atom/lib/views/menu-view.coffee:103:85)
    at ImdoneAtomView.module.exports.ImdoneAtomView.addPluginProjectButtons (/packages/imdone-atom/lib/views/imdone-atom-view.coffee:317:41)
    at ImdoneAtomView.module.exports.ImdoneAtomView.addPluginButtons (/packages/imdone-atom/lib/views/imdone-atom-view.coffee:298:6)
    at ImdoneAtomView.module.exports.ImdoneAtomView.updateBoard (/packages/imdone-atom/lib/views/imdone-atom-view.coffee:610:6)
    at ImdoneAtomView.module.exports.ImdoneAtomView.onRepoUpdate (/packages/imdone-atom/lib/views/imdone-atom-view.coffee:411:6)
    at /packages/imdone-atom/lib/views/imdone-atom-view.coffee:168:8
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at PluginViewInterface.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at /packages/imdone-atom/lib/views/imdone-atom-view.coffee:126:25)
    at emitOne (events.js:96:13)
    at Repository.emit (events.js:188:7)
    at fn (/packages/imdone-atom/node_modules/imdone-core/lib/repository.js:270:20)
    at _cb (/packages/imdone-atom/node_modules/imdone-core/lib/mixins/repo-fs-store.js:126:7)
    at /packages/imdone-atom/node_modules/graceful-fs/graceful-fs.js:43:10
    at /packages/linter-swagger/node_modules/graceful-fs/graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:123:15)
```

### Commands

```
     -1:25.4.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-nord-atom-syntax.theme-nord-atom-ui)
     -1:16.2.0 imdone-atom:tasks (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
```

### Non-Core Packages

```
aligner-css 1.2.0 
auto-update-packages 1.0.1 
clock 1.9.0 
cssfmt 1.4.0 
date 1.2.2 
file-icons 2.0.17 
git-hide 1.0.0 
git-log 0.4.1 
git-plus 7.3.3 
highlight-selected 0.12.0 
imdone-atom 2.1.21 
imdone-atom-github 0.1.11 
ink 0.6.4 
linter 1.11.23 
linter-clojure 1.1.2 
linter-swagger 0.3.9 
linter-write-good 0.8.0 
lisp-paredit 0.5.5 
markdown-writer 2.6.4 
minimap 4.26.8 
minimap-highlight-selected 4.5.0 
nord-atom-syntax 0.6.0 
nord-atom-ui 0.10.2 
Parinfer 1.17.0 
pretty-json 1.6.1 
proto-repl 1.4.16 
proto-repl-charts 0.4.0 
set-syntax 0.3.2 
swackets 0.26.0 
sync-settings 0.8.1 
tablr 1.8.1 
tool-bar 1.0.1 
tree-view-git-status 1.3.1 
```

**Comment by piascikj** [comment]
----

READY: Fix gh:213 and gh:219 by checking for undefined id:142
[**CHANGELOG.md:2**](https://github.com/imdone/imdone-atom/blob/master/CHANGELOG.md#L2)

@imdone *commenter*. The developer's task board. [imdone.io](https://imdone.io)

**Comment by piascikj** [comment]
DONE: Fix gh:213 and gh:219 by checking for undefined id:142
      [**CHANGELOG.md:2**](https://github.com/imdone/imdone-atom/blob/undefined/CHANGELOG.md#L2)  
@imdone *Issue Closer*. The developer's task board. [imdone.io](https://imdone.io)
