### ISSUE TITLE
Uncaught TypeError: Cannot set property 'connector' of undefined

### ISSUE THREAD

**Issue by Global-Open-Source** [imdone/imdone-atom#219]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.14.4 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.4
**Thrown From**: [imdone-atom](https://github.com/imdone/imdone-atom) package 2.1.21

### Stack Trace

Uncaught TypeError: Cannot set property 'connector' of undefined

```
At /Users/benjamin/.atom/packages/imdone-atom/lib/views/product-selection-view.coffee:87

TypeError: Cannot set property 'connector' of undefined
    at /packages/imdone-atom/lib/views/product-selection-view.coffee:87:7
    at /packages/imdone-atom/lib/services/connector-manager.coffee:70:14
    at /packages/imdone-atom/lib/services/imdoneio-client.coffee:247:14
    at Request.callback (/packages/imdone-atom/node_modules/superagent/lib/node/index.js:631:3)
    at /packages/imdone-atom/node_modules/superagent/lib/node/index.js:795:18
    at /packages/imdone-atom/node_modules/superagent/lib/node/parsers/json.js:16:7)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

### Commands

```
     -9:44.1.0 imdone-atom:tasks (div.package-detail.panels-item)
     -7:00.6.0 core:paste (input.form-control)
 14x -5:19.1.0 core:move-right (input.hidden-input)
 20x -5:16.7.0 core:backspace (input.hidden-input)
     -5:13.5.0 core:move-right (input.hidden-input)
     -5:12.8.0 core:backspace (input.hidden-input)
     -1:38 core:move-up (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -1:37.5.0 tree-view:expand-item (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
  6x -1:36.9.0 core:move-down (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -1:35.3.0 tree-view:expand-item (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
  3x -1:34.9.0 core:move-down (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
  5x -0:51.2.0 core:backspace (input.hidden-input)
  2x -0:15.9.0 core:move-left (input.hidden-input)
     -0:04.1.0 imdone-atom:tasks (div.package-detail.panels-item)
```

### Non-Core Packages

```
github-issues 0.7.1 
imdone-atom 2.1.21 
imdone-atom-github 0.1.11 
minimap 4.26.8 
minimap-bookmarks 0.4.2 
minimap-cursorline 0.2.0 
minimap-find-and-replace 4.5.2 
minimap-git-diff 4.3.1 
minimap-highlight-selected 4.5.0 
minimap-selection 4.4.0 
sass-autocompile 0.13.3 
```

**Comment by piascikj** [comment]
----

READY: Fix gh:213 and gh:219 by checking for undefined id:142
[**CHANGELOG.md:2**](https://github.com/imdone/imdone-atom/blob/master/CHANGELOG.md#L2)

@imdone *commenter*. The developer's task board. [imdone.io](https://imdone.io)

**Comment by piascikj** [comment]
DONE: Fix gh:213 and gh:219 by checking for undefined id:142
      [**CHANGELOG.md:2**](https://github.com/imdone/imdone-atom/blob/undefined/CHANGELOG.md#L2)  
@imdone *Issue Closer*. The developer's task board. [imdone.io](https://imdone.io)
