### ISSUE TITLE
Uncaught TypeError: Cannot read property 'isPathIgnored' of null

### ISSUE THREAD

**Issue by LukeXuan** [imdone/imdone-atom#22]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.7
**System**: Microsoft Windows 7 Ultimate 
**Thrown From**: [imdone-atom](https://github.com/imdone/imdone-atom) package, v1.1.27

### Stack Trace

Uncaught TypeError: Cannot read property 'isPathIgnored' of null

```
At C:\Users\Luke.Lazurite\.atom\packages\imdone-atom\lib\imdone-atom.coffee:88

TypeError: Cannot read property 'isPathIgnored' of null
  at Repository.module.exports.ImdoneAtom.excludeVcsIgnoresMixin.shouldExclude (C:\Users\Luke.Lazurite\.atom\packages\imdone-atom\lib\imdone-atom.coffee:88:29)
  at Repository.repo.fileOK (C:\Users\Luke.Lazurite\.atom\packages\imdone-atom\node_modules\imdone-core\lib\mixins\repo-fs-store.js:97:14)
  at C:\Users\Luke.Lazurite\.atom\packages\imdone-atom\node_modules\imdone-core\lib\mixins\repo-fs-store.js:206:14
  at replenish (C:\Users\Luke.Lazurite\AppData\Local\atom\app-1.0.7\resources\app.asar\node_modules\request\node_modules\form-data\node_modules\async\lib\async.js:191:21)
  at _eachLimit (C:\Users\Luke.Lazurite\AppData\Local\atom\app-1.0.7\resources\app.asar\node_modules\request\node_modules\form-data\node_modules\async\lib\async.js:208:15)
  at Object.async.eachLimit (C:\Users\Luke.Lazurite\AppData\Local\atom\app-1.0.7\resources\app.asar\node_modules\request\node_modules\form-data\node_modules\async\lib\async.js:168:12)
  at C:\Users\Luke.Lazurite\.atom\packages\imdone-atom\node_modules\imdone-core\lib\mixins\repo-fs-store.js:203:13
  at C:\Users\Luke.Lazurite\.atom\packages\imdone-atom\node_modules\imdone-core\lib\mixins\repo-fs-store.js:283:17
  at C:\Users\Luke.Lazurite\.atom\packages\imdone-atom\node_modules\imdone-core\lib\mixins\repo-fs-store.js:291:15
  at FSReqWrap.oncomplete (fs.js:77:15)

```

### Commands

```
     -0:31.2.0 core:save (atom-text-editor.editor.is-focused)
     -0:30.3.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:27.2.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:27.2.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:26.6.0 imdone-atom:tasks (atom-text-editor.editor.is-focused)
     -0:14.7.0 core:close (atom-pane.pane.active)
     -0:11.8.0 core:save (atom-text-editor.editor.is-focused)
     -0:10.9.0 imdone-atom:tasks (atom-text-editor.editor.is-focused)
     -0:09.0 core:close (atom-pane.pane.active)
     -0:08.2.0 command-palette:toggle (atom-text-editor.editor.is-focused)
  2x -0:06.4.0 core:move-down (atom-text-editor.editor.mini.is-focused)
  2x -0:05.5.0 core:move-up (atom-text-editor.editor.mini.is-focused)
     -0:05.1.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:04.7.0 core:move-up (atom-text-editor.editor.mini.is-focused)
     -0:04.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:04.4.0 imdone-atom:tasks (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-material-ui",
      "atom-material-syntax"
    ],
    "disabledPackages": [
      "npm-docs",
      "npm-docs",
      "npm-docs"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-material-syntax, v0.2.3
atom-material-ui, v0.6.0
atom-terminal-panel, v4.4.4
color-picker, v2.0.11
gulp-watcher, v0.1.0
imdone-atom, v1.1.27
language-arduino, v0.3.1
minimap, v4.13.1
pigments, v0.11.0
travis-ci-status, v0.16.0

# Dev
No dev packages
```

**Comment by LukeXuan** [comment]
Well, that's my fault. I didn't `git init` before calling imdone.
However, I didn't find any necessity of existence of git or other VCS, since the package works only on TODOs and so on/
