### ISSUE TITLE
Uncaught TypeError: Cannot read property 'id' of undefind

### ISSUE THREAD

**Issue by zigge** [imdone/imdone-atom#224]
I'm trying to generate the task board, but it keeps trying to sync with the webpage "imdone.io" and it fails. After this, I then try to do it again, but get the error described in the title. 

Stacktrace:

[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.3
**Thrown From**: [imdone-atom](https://github.com/imdone/imdone-atom) package 2.1.25

### Stack Trace

Uncaught TypeError: Cannot read property 'id' of undefined

```
At /Users/lassebjorklund/.atom/packages/imdone-atom/lib/views/product-selection-view.coffee:96

TypeError: Cannot read property 'id' of undefined
    at ProductSelectionView.module.exports.ProductSelectionView.saveDefaultConnector (/packages/imdone-atom/lib/views/product-selection-view.coffee:96:32)
    at ProductSelectionView.module.exports.ProductSelectionView.populateList (/packages/imdone-atom/lib/views/product-selection-view.coffee:18:6)
    at ProductSelectionView.module.exports.ProductSelectionView.setItems (/packages/imdone-atom/lib/views/product-selection-view.coffee:110:6)
    at /packages/imdone-atom/lib/views/share-tasks-view.coffee:51:22
    at ConnectorManager.module.exports.ConnectorManager.getProducts (/packages/imdone-atom/lib/services/connector-manager.coffee:36:14)
    at Repository.repo.getProducts (/packages/imdone-atom/lib/services/imdoneio-store.coffee:321:47)
    at ShareTasksView.module.exports.ShareTasksView.showProductPanel (/packages/imdone-atom/lib/views/share-tasks-view.coffee:49:17)
    at ShareTasksView.module.exports.ShareTasksView.onAuthenticated (/packages/imdone-atom/lib/views/share-tasks-view.coffee:33:28)
    at ShareTasksView.module.exports.ShareTasksView.show (/packages/imdone-atom/lib/views/share-tasks-view.coffee:31:6)
    at ShareTasksView.module.exports.ShareTasksView.initialize (/packages/imdone-atom/lib/views/share-tasks-view.coffee:27:6)
    at /packages/imdone-atom/node_modules/space-pen/lib/space-pen.js:184:25)
    at /packages/imdone-atom/lib/views/share-tasks-view.coffee:13:7)
    at Object.content (/packages/imdone-atom/lib/views/bottom-view.coffee:26:42)
    at Builder.tag (/packages/imdone-atom/node_modules/space-pen/lib/space-pen.js:281:19)
    at /packages/imdone-atom/node_modules/space-pen/lib/space-pen.js:83:49)
    at Object.content (/packages/imdone-atom/lib/views/bottom-view.coffee:25:10)
    at Builder.tag (/packages/imdone-atom/node_modules/space-pen/lib/space-pen.js:281:19)
    at /packages/imdone-atom/node_modules/space-pen/lib/space-pen.js:83:49)
    at Object.content (/packages/imdone-atom/lib/views/bottom-view.coffee:22:8)
    at Builder.tag (/packages/imdone-atom/node_modules/space-pen/lib/space-pen.js:281:19)
    at /packages/imdone-atom/node_modules/space-pen/lib/space-pen.js:83:49)
    at Function.module.exports.BottomView.content (/packages/imdone-atom/lib/views/bottom-view.coffee:16:6)
    at /packages/imdone-atom/node_modules/space-pen/lib/space-pen.js:156:31)
    at Function.View.buildHtml (/packages/imdone-atom/node_modules/space-pen/lib/space-pen.js:123:10)
    at /packages/imdone-atom/node_modules/space-pen/lib/space-pen.js:155:33)
    at /packages/imdone-atom/lib/views/bottom-view.coffee:8:5)
    at Object.content (/packages/imdone-atom/lib/views/imdone-atom-view.coffee:112:40)
    at Builder.tag (/packages/imdone-atom/node_modules/space-pen/lib/space-pen.js:281:19)
    at /packages/imdone-atom/node_modules/space-pen/lib/space-pen.js:83:49)
    at Object.content (/packages/imdone-atom/lib/views/imdone-atom-view.coffee:111:12)
    at Builder.tag (/packages/imdone-atom/node_modules/space-pen/lib/space-pen.js:281:19)
    at /packages/imdone-atom/node_modules/space-pen/lib/space-pen.js:83:49)
    at Object.content (/packages/imdone-atom/lib/views/imdone-atom-view.coffee:106:10)
    at Builder.tag (/packages/imdone-atom/node_modules/space-pen/lib/space-pen.js:281:19)
    at /packages/imdone-atom/node_modules/space-pen/lib/space-pen.js:83:49)
    at Object.content (/packages/imdone-atom/lib/views/imdone-atom-view.coffee:105:8)
    at Builder.tag (/packages/imdone-atom/node_modules/space-pen/lib/space-pen.js:281:19)
    at /packages/imdone-atom/node_modules/space-pen/lib/space-pen.js:83:49)
    at Function.module.exports.ImdoneAtomView.content (/packages/imdone-atom/lib/views/imdone-atom-view.coffee:82:6)
    at /packages/imdone-atom/node_modules/space-pen/lib/space-pen.js:156:31)
    at Function.View.buildHtml (/packages/imdone-atom/node_modules/space-pen/lib/space-pen.js:123:10)
    at /packages/imdone-atom/node_modules/space-pen/lib/space-pen.js:155:33)
    at /packages/imdone-atom/node_modules/atom-space-pen-views/lib/scroll-view.js:12:47)
    at /packages/imdone-atom/lib/views/imdone-atom-view.coffee:41:5)
    at Object.createImdoneAtomView (/packages/imdone-atom/lib/imdone-atom.coffee:195:16)
    at Object.viewForUri (/packages/imdone-atom/lib/imdone-atom.coffee:188:6)
    at /packages/imdone-atom/lib/imdone-atom.coffee:123:8
    at Workspace.module.exports.Workspace.openURIInPane (/app.asar/src/workspace.js:501:22)
    at Workspace.module.exports.Workspace.open (/app.asar/src/workspace.js:436:19)
    at Object.tasks (/packages/imdone-atom/lib/imdone-atom.coffee:140:20)
    at /packages/imdone-atom/lib/imdone-atom.coffee:109:8)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:259:29)
    at /app.asar/src/command-registry.js:3:59
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:599:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:390:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/app.asar/src/window-event-handler.js:106:36)
    at /app.asar/src/window-event-handler.js:3:59)
```

### Commands

```
     -3:42.2.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -3:12.5.0 platformio-ide:settings:pkg-platformio-ide (div.package-detail.panels-item)
     -2:58.4.0 intentions:highlight (input.hidden-input)
  2x -2:57.9.0 imdone-atom:tasks (input.hidden-input)
     -0:11.2.0 core:close (div.imdone-atom.pane-item)
     -0:10.4.0 intentions:highlight (input.hidden-input)
     -0:09.8.0 imdone-atom:tasks (input.hidden-input)
```

### Non-Core Packages

```
advanced-open-file 0.16.6 
atom-beautify 0.29.17 
atom-ternjs 0.18.2 
autoclose-html 0.23.0 
autocomplete-clang 0.10.0 
build 0.67.0 
busy 0.7.0 
busy-signal 1.3.0 
dash 1.7.1 
file-icons 2.1.2 
highlight-selected 0.13.1 
imdone-atom 2.1.25 
intentions 1.1.2 
language-ini 1.19.0 
linter 2.1.2 
linter-gcc 0.7.1 
linter-ui-default 1.2.2 
minimap 4.27.0 
minimap-highlight-selected 4.6.0 
platformio-ide 2.0.0-beta.2 
platformio-ide-terminal 2.5.0 
script 3.14.1 
tool-bar 1.1.0 
```

**Comment by piascikj** [comment]
I shortened the timeout for requests from 30 seconds to 20 seconds but if you have a lot of tasks it could take a while.  Tasks are sent to the server in batches of 20 using a max of two parallel requests.
