### ISSUE TITLE
Uncaught TypeError: callback is not a function

### ISSUE THREAD

**Issue by nodarai** [imdone/imdone-atom#227]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Windows 7
**Thrown From**: [imdone-atom](https://github.com/imdone/imdone-atom) package 2.2.3

### Stack Trace

Uncaught TypeError: callback is not a function

```
At C:\Users\***\.atom\packages\imdone-atom\node_modules\async\lib\async.js:649

TypeError: callback is not a function
    at /packages/imdone-atom/node_modules/async/lib/async.js:649:28
    at /packages/imdone-atom/lib/services/imdoneio-client.coffee:54:22
    at /packages/imdone-atom/lib/services/imdoneio-client.coffee:117:14
    at /packages/imdone-atom/lib/services/imdoneio-client.coffee:182:14
    at /packages/imdone-atom/node_modules/nedb/lib/executor.js:29:17)
    at Cursor.execFn (/packages/imdone-atom/node_modules/nedb/lib/datastore.js:520:14)
    at callback (/packages/imdone-atom/node_modules/nedb/lib/cursor.js:126:19)
    at /packages/imdone-atom/node_modules/nedb/lib/cursor.js:193:12
    at /packages/imdone-atom/node_modules/nedb/lib/datastore.js:329:14
    at Object.async.eachSeries (/packages/imdone-atom/node_modules/async/lib/async.js:130:20)
    at /packages/imdone-atom/node_modules/nedb/lib/datastore.js:323:11
    at fn (/packages/imdone-atom/node_modules/async/lib/async.js:582:34)
    at /packages/imdone-atom/node_modules/async/lib/async.js:498:34)
    at runCallback (timers.js:574:20)
    at tryOnImmediate (timers.js:554:5)
    at processImmediate [as _immediateCallback] (timers.js:533:5)
```

### Commands

```
     -0:37 tree-view:show (atom-workspace.workspace.scrollbars-visible-always.theme-solarized-dark-syntax.theme-one-dark-ui)
```

### Non-Core Packages

```
atom-django 0.3.2 
incremental-search 5.2.1 
language-htaccess 0.1.1 
language-ini 1.19.0 
pigments 0.39.1 
script 3.14.1 
synced-sidebar 0.4.3 
autoclose-tags 0.2.1 
autocomplete-bash-builtins 0.3.4 
autocomplete-python 1.8.30 
busy-signal 1.2.0 
color-picker 2.2.5 
d3 4.7.4 
django-atom 0.2.4 
file-icons 2.0.13 
fonts 2.0.0 
git-log 0.4.1 
git-time-machine 1.5.9 
highlight-line 0.12.0 
highlight-selected 0.12.0 
imdone-atom 2.2.3 
intentions 1.1.2 
linter 1.11.4 
linter-pylint 1.2.2 
linter-ui-default 0.0.3 
minimap 4.26.8 
minimap-highlight-selected 4.5.0 
minimap-pigments 0.2.2 
minimap-split-diff 0.3.7 
python-tools 0.6.9 
remote-edit 1.8.24 
split-diff 1.3.0 
symbols-tree-view 0.13.2 
tree-view-search-bar 0.1.3 
```

**Comment by piascikj** [comment]
Still getting this error?  Can you provide a way to reproduce?

**Comment by nodarai** [comment]
The error was shown on Atom launch and on iMdone Tasks.
On version 2.2.7 the error is gone.
