### ISSUE TITLE
Uncaught TypeError: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by danaras** [imdone/imdone-atom#231]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.5
**Thrown From**: [imdone-atom](https://github.com/imdone/imdone-atom) package 2.2.6

### Stack Trace

Uncaught TypeError: Cannot read property '0' of undefined

```
At /Users/Danara/.atom/packages/imdone-atom/lib/services/imdoneio-client.coffee:328

TypeError: Cannot read property '0' of undefined
    at /packages/imdone-atom/lib/services/imdoneio-client.coffee:328:51
    at arrayMap (/packages/imdone-atom/node_modules/lodash/lodash.js:660:23)
    at Function.map (/packages/imdone-atom/node_modules/lodash/lodash.js:9571:14)
    at ImdoneioClient.module.exports.ImdoneioClient.syncTasksForDelete (/packages/imdone-atom/lib/services/imdoneio-client.coffee:328:17)
    at /packages/imdone-atom/lib/services/imdoneio-store.coffee:115:20
    at /packages/imdone-atom/node_modules/imdone-core/lib/repository.js:1043:5
    at /packages/imdone-atom/node_modules/async/lib/async.js:726:13
    at /packages/imdone-atom/node_modules/async/lib/async.js:52:16
    at done (/packages/imdone-atom/node_modules/async/lib/async.js:246:17)
    at /packages/imdone-atom/node_modules/async/lib/async.js:44:16
    at /packages/imdone-atom/node_modules/async/lib/async.js:723:17
    at /packages/imdone-atom/node_modules/async/lib/async.js:167:37
    at /packages/imdone-atom/node_modules/imdone-core/lib/mixins/repo-fs-store.js:219:17
    at /packages/imdone-atom/node_modules/imdone-core/lib/repository.js:494:5
    at /packages/imdone-atom/node_modules/imdone-core/lib/mixins/repo-fs-store.js:113:11
    at /packages/imdone-atom/node_modules/isbinaryfile/index.js:21:24
    at /Applications/Atom.app/Contents/Resources/app/node_modules/graceful-fs/graceful-fs.js:43:10
    at /Applications/Atom.app/Contents/Resources/app/node_modules/graceful-fs/graceful-fs.js:43:10
    at /Applications/Atom.app/Contents/Resources/app/node_modules/graceful-fs/graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:123:15)
```

### Commands

```
  2x -9:55.9.0 core:backspace (input.hidden-input)
     -8:55.6.0 core:select-all (input.hidden-input)
     -8:51.8.0 window:decrease-font-size (input.hidden-input)
     -8:45.3.0 core:select-all (input.hidden-input)
     -8:43 window:decrease-font-size (input.hidden-input)
     -8:40.8.0 window:reset-font-size (input.hidden-input)
  3x -8:36.9.0 window:decrease-font-size (input.hidden-input)
     -8:30.5.0 window:increase-font-size (input.hidden-input)
  2x -5:56.3.0 whitespace:remove-trailing-whitespace (input.hidden-input)
     -5:36.2.0 styleguide:show (input.hidden-input)
     -5:10.4.0 imdone-atom:tasks (div.styleguide.pane-item.native-key-bindings)
```

### Non-Core Packages

```
atom-beautify 0.30.3 
autoclose-html 0.23.0 
file-icons 2.1.8 
Hydrogen 1.19.0 
imdone-atom 2.2.6 
json-path-finder 0.1.9 
markdown-pdf 1.5.4 
minimap 4.28.2 
seti-ui 1.9.0 
vim-mode 0.66.0 
```

**Comment by piascikj** [comment]
Is this still an issue?
