### ISSUE TITLE
Uncaught TypeError: Cannot set property 'name' of undefined

### ISSUE THREAD

**Issue by ShMcK** [imdone/imdone-atom#32]
[Enter steps to reproduce below:]

1. Created task called "Title"
2. Deleted task called "Title"
3. Tried to add a new task called "Title"

**Atom Version**: 1.0.11
**System**: Mac OS X 10.10.5
**Thrown From**: [imdone-atom](https://github.com/imdone/imdone-atom) package, v1.1.37

### Stack Trace

Uncaught TypeError: Cannot set property 'name' of undefined

```
At /Users/shmck/.atom/packages/imdone-atom/node_modules/imdone-core/lib/repository.js:779

TypeError: Cannot set property 'name' of undefined
  at Repository.renameList (/Users/shmck/.atom/packages/imdone-atom/node_modules/imdone-core/lib/repository.js:779:30)
  at ConfigView.module.exports.ConfigView.doListRename (/Users/shmck/.atom/packages/imdone-atom/lib/config-view.coffee:77:17)
  at HTMLButtonElement.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:220:36)
  at HTMLButtonElement.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
  at HTMLButtonElement.elemData.handle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)

```

### Commands

```
     -1:44.2.0 core:move-left (atom-text-editor.editor.is-focused)
  9x -1:43.8.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:37.3.0 core:save (atom-text-editor.editor.is-focused)
  5x -1:25.2.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:19.6.0 snippets:expand (atom-text-editor.editor.is-focused.autocomplete-active)
 19x -1:15.6.0 core:move-left (atom-text-editor.editor.is-focused.autocomplete-active)
  4x -1:13.2.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:09.1.0 core:save (atom-text-editor.editor.is-focused)
  8x -0:53.2.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:51.6.0 editor:select-to-end-of-line (atom-text-editor.editor.is-focused)
  2x -0:51.3.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:43.3.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -0:43.3.0 docblockr:parse-enter (atom-text-editor.editor.is-focused)
  3x -0:42.7.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:40.1.0 core:save (atom-text-editor.editor.is-focused)
 10x -0:20.8.0 core:backspace (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
.bin, vundefined
atom-beautify, v0.28.11
atom-typescript, v6.0.5
atom-wallaby, v1.0.4
auto-update-packages, v1.0.0
autoclose-html, v0.19.0
docblockr, v0.7.3
emmet, v2.3.12
file-icons, v1.6.9
highlight-line, v0.11.0
highlight-selected, v0.10.1
imdone-atom, v1.1.37
jshint, v1.6.1
linter, v1.5.1
pigments, v0.14.0
project-manager, v2.5.1
save-session, v0.15.7

# Dev
No dev packages
```

**Comment by piascikj** [comment]
Looks like you must have clicked the list name first, which opened the rename list dialog.  Then after opening the rename dialog, you deleted the list.  When you clicked save, the list wasn't there to rename.  I'll put in a change to listen for list deletes and close the rename dialog if it's open for a list that was just deleted.

Thanks for bringing this to my attention!
