### ISSUE TITLE
Uncaught TypeError: Cannot read property 'schedule' of undefined

### ISSUE THREAD

**Issue by chrisaalid** [imdone/imdone-atom#360]
1. imdone has stopped working in Atom for me. Issue occurs whenever I run the 'Imdone Atom: Tasks' command. This persists even after uninstalling/reinstalling the package.

**Atom**: 1.25.0 x64
**Electron**: 1.7.11
**OS**: Mac OS X 10.13.2
**Thrown From**: [imdone-atom](https://github.com/imdone/imdone-atom) package 2.4.0

### Stack Trace

Uncaught TypeError: Cannot read property 'schedule' of undefined

```
At /Users/p608oxs-129l/.atom/packages/imdone-atom/lib/views/imdone-atom-view.coffee:425

TypeError: Cannot read property 'schedule' of undefined
    at /packages/imdone-atom/lib/views/imdone-atom-view.coffee:425:28
    at Repository.transformTasks (/packages/imdone-atom/lib/services/imdoneio-store.coffee:89:12)
    at ImdoneAtomView.module.exports.ImdoneAtomView.onRepoUpdate (/packages/imdone-atom/lib/views/imdone-atom-view.coffee:424:17)
    at /packages/imdone-atom/lib/views/imdone-atom-view.coffee:169:8
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at PluginViewInterface.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at /packages/imdone-atom/lib/views/imdone-atom-view.coffee:125:25)
    at emitOne (events.js:96:13)
    at Repository.emit (events.js:191:7)
    at fn (/packages/imdone-atom/node_modules/imdone-core/lib/repository.js:269:20)
    at _cb (/packages/imdone-atom/node_modules/imdone-core/lib/mixins/repo-fs-store.js:131:7)
    at /app.asar/node_modules/graceful-fs/graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:114:15)
```

### Commands

```
     -0:03.5.0 command-palette:toggle (div.package-detail.panels-item)
     -0:02.0 core:confirm (input.hidden-input)
     -0:02.0 imdone-atom:tasks (div.package-detail.panels-item)
```

### Non-Core Packages

```
awiki 0.3.1 
document-outline 2.1.1 
foldingtext-for-atom 0.9.2 
hyperclick 0.1.5 
imdone-atom 2.4.0 
language-markdown 0.25.1 
language-todotxt 1.0.2 
markdown-fold 0.2.0 
markdown-image-assistant 0.2.0 
markdown-pdf 2.1.0 
markdown-table-formatter 2.9.2 
markdown-toc 0.4.2 
markdown-writer 2.7.3 
pandoc-convert 1.1.1 
sort-lines 0.18.0 
```

**Comment by piascikj** [comment]
Implementing a fix now

**Comment by piascikj** [comment]
Should work in 2.4.1.  Let me know if it's working.

**Comment by chrisaalid** [comment]
@piascikj that fixed it completely. Thanks!

**Comment by kelserj** [comment]
Just ran into this one.
