### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getContent' of undefined

### ISSUE THREAD

**Issue by kelserj** [imdone/imdone-atom#368]
[Enter steps to reproduce:]

1. Clicked on TODO list and this happened. 
2. ...

**Atom**: 1.25.0 x64
**Electron**: 1.7.11
**OS**: Mac OS X 10.13.3
**Thrown From**: [imdone-atom](https://github.com/imdone/imdone-atom) package 2.4.2

### Stack Trace

Uncaught TypeError: Cannot read property 'getContent' of undefined

```
At /Users/jkelser/.atom/packages/imdone-atom/node_modules/imdone-core/lib/repository.js:947

TypeError: Cannot read property 'getContent' of undefined
    at Repository.modifyTask (/packages/imdone-atom/node_modules/imdone-core/lib/repository.js:947:12)
    at /packages/imdone-atom/lib/services/imdoneio-store.coffee:100:14
    at /packages/markdown-preview-plus/node_modules/async/lib/async.js:356:13
    at iterate (/packages/markdown-preview-plus/node_modules/async/lib/async.js:262:13)
    at async.forEachOfSeries.async.eachOfSeries (/packages/markdown-preview-plus/node_modules/async/lib/async.js:281:9)
    at _asyncMap (/packages/markdown-preview-plus/node_modules/async/lib/async.js:355:9)
    at Object.mapSeries (/packages/markdown-preview-plus/node_modules/async/lib/async.js:347:20)
    at /packages/imdone-atom/lib/services/imdoneio-store.coffee:99:13
    at gotConditionResult (/packages/imdone-atom/node_modules/wait-until/index.js:62:25)
    at /packages/imdone-atom/node_modules/wait-until/index.js:73:25
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

### Commands

```
  2x -4:06.3.0 core:backspace (input.hidden-input)
     -4:03.6.0 core:confirm (input.hidden-input)
  6x -4:02.6.0 core:backspace (input.hidden-input)
     -3:36.2.0 core:delete (input.hidden-input)
     -3:34.3.0 core:save (input.hidden-input)
     -3:20.2.0 imdone-atom:tasks (div.imdone-atom.pane-item)
     -3:02.6.0 core:select-down (input.hidden-input)
     -3:01.4.0 core:delete (input.hidden-input)
     -3:00.3.0 core:save (input.hidden-input)
     -1:55.8.0 core:move-up (input.hidden-input)
     -1:54.8.0 core:select-down (input.hidden-input)
  2x -1:52.9.0 core:move-down (input.hidden-input)
     -1:52.1.0 core:move-up (input.hidden-input)
```

### Non-Core Packages

```
atom-cli-diff 1.9.0 
busy-signal 1.4.3 
file-icons 2.1.18 
foldingtext-for-atom 0.9.2 
fountain 0.7.2 
imdone-atom 2.4.2 
intentions 1.1.5 
language-eml 0.8.0 
language-log 1.10.1 
language-oracle 1.9.0 
line-ending-converter 1.3.2 
linter 2.2.0 
linter-proselint 3.3.0 
linter-ui-default 1.7.1 
markdown-preview-plus 2.5.6 
markdown-table-formatter 2.9.2 
marked 0.1.10 
multi-cursor 2.1.5 
open-recent 5.0.0 
pandoc-convert 1.1.1 
pdf-view 0.67.0 
print-atom 0.1.1 
project-manager 3.3.5 
run-command2 1.12.2 
todo-show 2.2.0 
```

**Comment by kelserj** [comment]
I had moved a bunch of files into an excluded directory while imdone was open.
