### ISSUE TITLE
Uncaught TypeError: Cannot set property 'Sortable1446114867910' of null

### ISSUE THREAD

**Issue by filjoseph1989** [imdone/imdone-atom#38]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.19
**System**: Microsoft Windows 10 Home
**Thrown From**: [imdone-atom](https://github.com/imdone/imdone-atom) package, v1.1.50

### Stack Trace

Uncaught TypeError: Cannot set property 'Sortable1446114867910' of null

```
At C:\Users\User\.atom\packages\imdone-atom\node_modules\sortablejs\Sortable.js:854

TypeError: Cannot set property 'Sortable1446114867910' of null
  at Sortable.destroy (C:\Users\User\.atom\packages\imdone-atom\node_modules\sortablejs\Sortable.js:854:16)
  at MenuView.module.exports.MenuView.updateMenu (C:\Users\User\.atom\packages\imdone-atom\lib\menu-view.coffee:68:20)
  at Repository.<anonymous> (C:\Users\User\.atom\packages\imdone-atom\lib\menu-view.coffee:33:41)
  at emitOne (events.js:82:20)
  at Repository.emit (events.js:169:7)
  at fn (C:\Users\User\.atom\packages\imdone-atom\node_modules\imdone-core\lib\repository.js:252:20)
  at C:\Users\User\.atom\packages\quick-editor\node_modules\chokidar\node_modules\readdirp\node_modules\graceful-fs\graceful-fs.js:42:10
  at FSReqWrap.oncomplete (fs.js:82:15)

```

### Commands

```
     -7:58.5.0 core:save (span.ft-body-text)
  5x -6:04.7.0 window:decrease-font-size (ft-outline-editor#QJlA7imNhe.text-mode)
 12x -3:49.3.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -3:44.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -2:56.1.0 command-palette:toggle (div.settings-view.pane-item)
     -2:51.1.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -2:51.1.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -2:16.5.0 command-palette:toggle (div.settings-view.pane-item)
     -2:10.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -2:10.1.0 expose:toggle (div.settings-view.pane-item)
  4x -2:00.1.0 core:move-right (div.expose-view.animate.visible)
  4x -1:56.6.0 core:move-left (div.expose-view.animate.visible)
     -1:22.8.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -1:15.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:15.5.0 imdone-atom:tasks (atom-text-editor.editor)
  5x -0:16.2.0 core:backspace (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true
  }
}
```

### Installed Packages

```coffee
# User
aligner, v0.17.1
atomatigit, v1.5.5
color-picker, v2.0.13
emmet, v2.3.13
expose, v0.9.0
imdone-atom, v1.1.50
language-diff, v0.3.1
minimap, v4.15.0
php-cs-fixer, v2.5.1
quick-editor, v0.4.3
remote-edit, vundefined
sync-settings, v0.6.0

# Dev
No dev packages
```

**Comment by piascikj** [comment]
Not sure how this happened.  Can you reproduce?
