### ISSUE TITLE
Uncaught TypeError: Cannot read property 'source' of undefined

### ISSUE THREAD

**Issue by blay** [imdone/imdone-atom#381]
1. Task list open. No other packages in atom except themes.
2. Move a card to a new column (i.e. from TODO to DONE) OR move the priority of a card up or down a list.
3. Sometimes works, sometime get error "Uncaught TypeError: Cannot read property 'source' of undefined"
4. Task list freezes and circles forever.
5. Close task list and open it again. Rescans and the card is in the new location as should be.

**Atom**: 1.27.2 x64
**Electron**: 1.7.15
**OS**: Ubuntu 18.04
**Thrown From**: [imdone-atom](https://github.com/imdone/imdone-atom) package 2.4.29

### Stack Trace

Uncaught TypeError: Cannot read property 'source' of undefined

```
At /home/svartfax/.atom/packages/imdone-atom/node_modules/imdone-core/lib/repository.js:524

TypeError: Cannot read property 'source' of undefined
    at Repository.getTask (/packages/imdone-atom/node_modules/imdone-core/lib/repository.js:524:29)
    at /packages/imdone-atom/lib/views/imdone-atom-view.coffee:604:25)
    at Function.each (/packages/imdone-atom/node_modules/jquery/dist/jquery.js:374:23)
    at jQuery.fn.init.each (/packages/imdone-atom/node_modules/jquery/dist/jquery.js:139:17)
    at ImdoneAtomView.module.exports.ImdoneAtomView.replaceTasksInList (/packages/imdone-atom/lib/views/imdone-atom-view.coffee:602:34)
    at fn (/packages/imdone-atom/lib/views/imdone-atom-view.coffee:187:12)
    at /packages/imdone-atom/lib/views/imdone-atom-view.coffee:183:7
    at Function.module.exports.Emitter.simpleDispatch (/snap/atom/159/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at PluginViewInterface.module.exports.Emitter.emit (/snap/atom/159/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at /packages/imdone-atom/lib/views/imdone-atom-view.coffee:128:25)
    at emitOne (events.js:96:13)
    at Repository.emit (events.js:191:7)
    at /packages/imdone-atom/lib/services/imdoneio-store.coffee:202:12
    at /packages/imdone-atom/node_modules/imdone-core/lib/repository.js:1046:7
    at async.parallel (/packages/imdone-atom/node_modules/imdone-core/lib/repository.js:1077:5)
    at /packages/imdone-atom/node_modules/async/lib/async.js:726:13
    at /packages/imdone-atom/node_modules/async/lib/async.js:52:16
    at done (/packages/imdone-atom/node_modules/async/lib/async.js:246:17)
    at /packages/imdone-atom/node_modules/async/lib/async.js:44:16
    at /packages/imdone-atom/node_modules/async/lib/async.js:723:17
    at /packages/imdone-atom/node_modules/async/lib/async.js:167:37
    at /packages/imdone-atom/node_modules/imdone-core/lib/mixins/repo-fs-store.js:225:17
    at /packages/imdone-atom/node_modules/imdone-core/lib/repository.js:487:5
    at /packages/imdone-atom/node_modules/imdone-core/lib/mixins/repo-fs-store.js:118:11
    at /packages/imdone-atom/node_modules/isbinaryfile/index.js:21:24
    at /app.asar/node_modules/graceful-fs/graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:114:15)
```

### Commands

```
     -0:55.5.0 core:close (input.hidden-input)
  3x -0:27 core:delete (input.hidden-input)
     -0:24.3.0 editor:move-to-end-of-screen-line (input.hidden-input)
  3x -0:22.5.0 core:backspace (input.hidden-input)
     -0:21.4.0 core:save (input.hidden-input)
     -0:19.1.0 core:close (input.hidden-input)
```

### Non-Core Packages

```
atom-material-syntax 1.0.8 
atom-material-syntax-dark 1.0.0 
atom-material-syntax-light 0.4.6 
atom-material-ui 2.1.3 
imdone-atom 2.4.29 
```

**Comment by raghav-kukreti** [comment]
I experienced the same error but after closing the error alert and the IMDONE tab and pressing ```alt + t```
again, I see it updated.

**Comment by aubergine10** [comment]
Also got this error when clicking a "Down arrow" above the to-do list to see what it would do.

![imdone](https://user-images.githubusercontent.com/1386719/57587847-b8f61f00-7503-11e9-8af5-d6f36f4ee2c1.jpg)

After closing error popup and imdone tab, then reopening things seem to be working again.

**Comment by piascikj** [comment]
I'm no longer maintaining imdone-atom, but a stand alone electron app is available at [imdone.io](https://imdone.io)
