### ISSUE TITLE
Uncaught TypeError: Cannot read property 'map' of undefined

### ISSUE THREAD

**Issue by Jargon4072** [imdone/imdone-atom#386]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.30.0 x64
**Electron**: 2.0.5
**OS**: Microsoft Windows 10 Home Single Language
**Thrown From**: [imdone-atom](https://github.com/imdone/imdone-atom) package 2.4.31

### Stack Trace

Uncaught TypeError: Cannot read property 'map' of undefined

```
At C:\Users\__user.name__\.atom\packages\imdone-atom\lib\services\imdoneio-store.coffee:187

TypeError: Cannot read property 'map' of undefined
    at getIdsForList (/packages/imdone-atom/lib/services/imdoneio-store.coffee:187:10)
    at sortBySyncId (/packages/imdone-atom/lib/services/imdoneio-store.coffee:190:11)
    at Repository.repo.getTasksInList (/packages/imdone-atom/lib/services/imdoneio-store.coffee:215:5)
    at ImdoneAtomView.module.exports.ImdoneAtomView.getList (/packages/imdone-atom/lib/views/imdone-atom-view.coffee:581:18)
    at ImdoneAtomView.getList (/packages/imdone-atom/lib/views/imdone-atom-view.coffee:1:1)
    at /packages/imdone-atom/lib/views/imdone-atom-view.coffee:665:24)
    at /packages/git-plus/node_modules/jquery/dist/jquery.js:5380:24)
    at Function.each (/packages/git-plus/node_modules/jquery/dist/jquery.js:374:23)
    at jQuery.fn.init.each (/packages/git-plus/node_modules/jquery/dist/jquery.js:139:17)
    at jQuery.fn.init.domManip (/packages/git-plus/node_modules/jquery/dist/jquery.js:5377:16)
    at jQuery.fn.init.append (/packages/git-plus/node_modules/jquery/dist/jquery.js:5218:15)
    at ImdoneAtomView.module.exports.ImdoneAtomView.updateBoard (/packages/imdone-atom/lib/views/imdone-atom-view.coffee:665:12)
    at /packages/imdone-atom/lib/views/imdone-atom-view.coffee:472:8
    at Repository.transformTasks (/packages/imdone-atom/lib/services/imdoneio-store.coffee:91:12)
    at ImdoneAtomView.module.exports.ImdoneAtomView.onRepoUpdate (/packages/imdone-atom/lib/views/imdone-atom-view.coffee:471:17)
    at ImdoneAtomView.module.exports.ImdoneAtomView.initImdone (/packages/imdone-atom/lib/views/imdone-atom-view.coffee:451:8)
    at /packages/imdone-atom/lib/views/imdone-atom-view.coffee:65:10
    at /packages/imdone-atom/node_modules/imdone-core/lib/mixins/repo-fs-store.js:93:11
    at /packages/imdone-atom/node_modules/recursive-readdir/index.js:81:22
    at /packages/imdone-atom/node_modules/recursive-readdir/index.js:81:22
    at /packages/imdone-atom/node_modules/recursive-readdir/index.js:81:22
    at /packages/imdone-atom/node_modules/recursive-readdir/index.js:81:22
    at /packages/imdone-atom/node_modules/recursive-readdir/index.js:88:20
    at FSReqWrap.oncomplete (fs.js:153:5)
```

### Commands

```
     -0:30.7.0 imdone-atom:tasks (div.panels-item)
```

### Non-Core Packages

```
ask-stack 2.2.0 
atom-beautify 0.33.1 
atom-clock 0.1.16 
atom-css-comb 3.3.1 
atom-monokai 0.10.9 
autocomplete-paths 2.12.2 
bottom-dock 0.4.4 
busy-signal 1.4.3 
color-picker 2.3.0 
data-atom 0.29.0 
docblockr 0.13.7 
emmet 2.4.3 
expose 0.15.0 
file-icons 2.1.24 
git-plus 8.1.0 
git-time-machine 2.1.0 
gpp-compiler 3.0.7 
highlight-selected 0.14.0 
Hydrogen 2.5.1 
imdone-atom 2.4.31 
intentions 1.1.5 
language-docker 1.1.8 
linter 2.2.0 
linter-clang 4.1.2 
linter-cpplint 2.0.1 
linter-eslint 8.4.1 
linter-pylama 0.10.1 
linter-ui-default 1.7.1 
livestyle-atom 0.2.10 
merge-conflicts 1.4.5 
minimap 4.29.8 
minimap-highlight-selected 4.6.1 
monokai 0.24.0 
monokai-dark 1.5.0 
pigments 0.40.2 
platformio-ide-terminal 2.8.4 
project-manager 3.3.6 
project-plus 1.0.0 
script 3.18.1 
teletype 0.13.3 
todo 0.6.0 
todo-manager 0.2.10 
todo-show 2.3.2 
tomatimer 1.2.3 
tool-bar 1.1.10 
tool-bar-almighty 0.8.2 
wakatime 7.0.5 
```

**Comment by bartalamu** [comment]
I have the same issue, how to resolve it?
