### ISSUE TITLE
Uncaught Error: marked(): input parameter is of type [object Error], string expected

### ISSUE THREAD

**Issue by uuur86** [imdone/imdone-atom#394]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.40.1 x64
**Electron**: 3.1.10
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [imdone-atom](https://github.com/imdone/imdone-atom) package 2.4.33

### Stack Trace

Uncaught Error: marked(): input parameter is of type [object Error], string expected

```
At C:\Users\uqur\AppData\Local\atom\app-1.40.1\resources\app\static\<embedded>:14

Error: marked(): input parameter is of type [object Error], string expected
    at marked (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:14:560661)
    at NotificationElement.render (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:905214)
    at new NotificationElement (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:902977)
    at Object.createView (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:219616)
    at ViewRegistry.createView (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:324212)
    at ViewRegistry.getView (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:323834)
    at Object.addNotificationView (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:220937)
    at ~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:217293
    at Function.simpleDispatch (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:1209208)
    at Emitter.emit (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:1210649)
    at NotificationManager.addNotification (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:326767)
    at NotificationManager.addWarning (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:326481)
    at /packages/imdone-atom/lib/views/imdone-atom-view.coffee:195:56
    at Function.simpleDispatch [as dispatch] (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:1209208)
    at PluginViewInterface.emit (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:1210649)
    at /packages/imdone-atom/lib/views/imdone-atom-view.coffee:127:25)
    at Repository.emit (events.js:182:13)
    at /packages/imdone-atom/node_modules/imdone-core/lib/mixins/repo-fs-store.js:68:25
    at /packages/imdone-atom/node_modules/imdone-core/lib/repository.js:723:25
    at /packages/imdone-atom/node_modules/imdone-core/lib/mixins/repo-fs-store.js:257:23
    at /packages/imdone-atom/node_modules/recursive-readdir/index.js:75:22
    at /packages/imdone-atom/node_modules/recursive-readdir/index.js:75:22
    at /packages/imdone-atom/node_modules/recursive-readdir/index.js:44:14
    at FSReqWrap.oncomplete (fs.js:169:20)
```

### Commands

```
```

### Non-Core Packages

```
atom-material-syntax 1.0.8 
atom-material-ui 2.1.3 
highlight-selected 0.16.0 
ide-php 0.7.18 
imdone-atom 2.4.33 
language-php-no-dollar-highlight 0.2.0 
php-cs-fixer 4.1.1 
pigments 0.40.2 
Sublime-Style-Column-Selection 1.7.5 
wordpress-suite 1.3.0 
```

**Comment by piascikj** [comment]
Sorry, I'm no longer maintaining imdone-atom.  I'm selling a stand alone version that works with any text editor at [imdone.io](https://imdone.io)

**Comment by uuur86** [comment]
ok, thank you for your answer
