### ISSUE TITLE
Uncaught TypeError: Cannot read property 'removeEventListener' of null

### ISSUE THREAD

**Issue by Braunson** [imdone/imdone-atom#43]
[Enter steps to reproduce below:]
1. Moved card on imdone tab from one column to another

**Atom Version**: 1.2.1
**System**: Microsoft Windows 8.1
**Thrown From**: [imdone-atom](https://github.com/imdone/imdone-atom) package, v1.2.0
### Stack Trace

Uncaught TypeError: Cannot read property 'removeEventListener' of null

```
At C:\Users\braunson\Dropbox\.atom\packages\imdone-atom\node_modules\sortablejs\Sortable.js:930

TypeError: Cannot read property 'removeEventListener' of null
    at _off (C:\Users\braunson\Dropbox\.atom\packages\imdone-atom\node_modules\sortablejs\Sortable.js:930:5)
    at Sortable._onDrop (C:\Users\braunson\Dropbox\.atom\packages\imdone-atom\node_modules\sortablejs\Sortable.js:677:4)
    at Sortable.handleEvent (C:\Users\braunson\Dropbox\.atom\packages\imdone-atom\node_modules\sortablejs\Sortable.js:759:10)
```
### Commands

```
  2x -4:27.8.0 core:close (atom-text-editor.editor.is-focused)
     -3:30.3.0 command-palette:toggle (atom-pane.pane.active)
     -3:28.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -3:28.8.0 settings-view:open (atom-pane.pane.active)
     -3:15.6.0 core:backspace (atom-text-editor#core.ignoredNames.editor.mini.is-focused)
     -2:36.7.0 core:select-all (atom-text-editor.editor.mini.is-focused)
     -2:28.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -2:00.8.0 core:close (div.package-readme.native-key-bindings)
     -1:59.2.0 imdone-atom:tasks (atom-pane.pane.active)
  4x -1:32.5.0 core:page-up (atom-pane.pane.active)
```
### Config

``` json
{
  "core": {
    "autoHideMenuBar": true,
    "themes": [
      "one-dark-ui",
      "atom-light-syntax"
    ]
  },
  "imdone-atom": {}
}
```
### Installed Packages

``` coffee
# User
aligner, v0.17.1
aligner-css, v1.2.0
aligner-php, v1.0.0
aligner-scss, v1.1.0
atom-beautify, vundefined
atom-shortcuts, v0.0.2
autocomplete-paths, v1.0.2
autocomplete-php, v0.3.7
color-picker, v2.0.13
devdocs, v0.2.1
docblockr, v0.7.3
editor-stats, v0.17.0
file-icons, v1.6.11
flex-tool-bar, v0.6.0
highlight-line, v0.11.0
highlight-selected, v0.11.1
imdone-atom, v1.2.0
imdone-atom-github, v0.1.4
jshint, v1.8.3
linter, v1.11.2
linter-php, v1.1.1
minimap, v4.16.0
minimap-bookmarks, v0.1.0
minimap-git-diff, v4.1.8
minimap-highlight-selected, v4.3.1
minimap-pigments, v0.1.7
php-cs-fixer, v2.5.1
pigments, vundefined
Remote-FTP, v0.7.10
tabs-to-spaces, v0.11.1
tool-bar, v0.1.9
tool-bar-main, v0.0.8
tree-view-git-modified, v0.6.0

# Dev
No dev packages
```

**Comment by piascikj** [comment]
I just updated sortable.js .  Maybe that will fix it.

**Comment by piascikj** [comment]
Are you still getting this error?
