### ISSUE TITLE
Uncaught Error: listen EADDRINUSE :::9799

### ISSUE THREAD

**Issue by piascikj** [imdone/imdone-atom#51]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.2.4
**System**: Ubuntu 14.04.3
**Thrown From**: [imdone-atom](https://github.com/imdone/imdone-atom) package, v1.3.1

### Stack Trace

Uncaught Error: listen EADDRINUSE :::9799

```
At events.js:141

Error: listen EADDRINUSE :::9799
    at Object.exports._errnoException (util.js:837:11)
    at exports._exceptionWithHostPort (util.js:860:20)
    at Server._listen2 (net.js:1231:14)
    at listen (net.js:1267:10)
    at Server.listen (net.js:1363:5)
    at Function.listen (/home/jesse/projects/imdone-atom/node_modules/engine.io/lib/engine.io.js:102:10)
    at Object.module.exports.init (/home/jesse/projects/imdone-atom/lib/socket-server.coffee:9:22)
    at Object.module.exports.ImdoneAtom.activate (/home/jesse/projects/imdone-atom/lib/imdone-atom.coffee:51:22)
    at Package.module.exports.Package.activateNow (/usr/share/atom/resources/app.asar/src/package.js:170:19)
    at /usr/share/atom/resources/app.asar/src/package.js:150:32
    at Package.module.exports.Package.measure (/usr/share/atom/resources/app.asar/src/package.js:92:15)
    at /usr/share/atom/resources/app.asar/src/package.js:143:26
    at Package.module.exports.Package.activate (/usr/share/atom/resources/app.asar/src/package.js:140:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/usr/share/atom/resources/app.asar/src/package-manager.js:512:21)
    at /usr/share/atom/resources/app.asar/src/package-manager.js:495:29
    at Config.module.exports.Config.transact (/usr/share/atom/resources/app.asar/src/config.js:311:16)
    at PackageManager.module.exports.PackageManager.activatePackages (/usr/share/atom/resources/app.asar/src/package-manager.js:490:19)
    at PackageManager.module.exports.PackageManager.activate (/usr/share/atom/resources/app.asar/src/package-manager.js:474:46)
    at AtomEnvironment.module.exports.AtomEnvironment.startEditorWindow (/usr/share/atom/resources/app.asar/src/atom-environment.js:671:21)
    at Object.<anonymous> (/usr/share/atom/resources/app.asar/src/initialize-application-window.js:38:8)
    at Object.<anonymous> (/usr/share/atom/resources/app.asar/src/initialize-application-window.js:49:4)
    at Module._compile (module.js:434:26)
    at Object.defineProperty.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:190:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at setupWindow (file:///usr/share/atom/resources/app.asar/static/index.js:79:5)
    at window.onload (file:///usr/share/atom/resources/app.asar/static/index.js:35:9)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "browser-plus",
      "browser-plus"
    ],
    "projectHome": "/home/jesse/projects",
    "excludeVcsIgnoredPaths": false
  },
  "imdone-atom": {
    "maxFilesPrompt": 2500,
    "fileOpeners": {},
    "openIn": {
      "intellij": "*. (java|groovy|gradle)"
    },
    "excludeVcsIgnoredPaths": false
  }
}
```

### Installed Packages

```coffee
# User
.bin, vundefined
atom-typescript, v7.12.1
custom-title, v1.0.1
drop-up, v0.4.0
file-icons, v1.6.12
imdone-atom, v1.3.1
imdone-atom-github, v0.1.5
language-groovy, v0.4.0
linter, v1.11.3
markdown-table-formatter, v2.5.5
minimap, v4.16.2
pigments, v0.19.1
terminal-panel, v1.14.1

# Dev
No dev packages
```

**Comment by piascikj** [comment]
Fixed
