### ISSUE TITLE
Uncaught TypeError: Cannot read property 'indexOf' of undefined

### ISSUE THREAD

**Issue by claytonrcarter** [imdone/imdone-atom#54]
Seems to related to trying to figure out the current project of a new/unsaved/untitled file:

1. Open a project/folder/repo in Atom
2. Open a new file (Cmd-n)
3. Issue command "IMDone Atom: Tasks" or use keys (Shift+Ctrl+t)

Switching to an existing file in the project and trying again will bring up the task list as expected.

**Atom Version**: 1.2.4
**System**: Mac OS X 10.10.2
**Thrown From**: [imdone-atom](https://github.com/imdone/imdone-atom) package, v1.3.3

### Stack Trace

Uncaught TypeError: Cannot read property 'indexOf' of undefined

```
At /Users/crcarter/.atom/packages/imdone-atom/lib/imdone-atom.coffee:76

TypeError: Cannot read property 'indexOf' of undefined
    at Object.module.exports.ImdoneAtom.getCurrentProject (/Users/crcarter/.atom/packages/imdone-atom/lib/imdone-atom.coffee:76:72)
    at Object.module.exports.ImdoneAtom.uriForProject (/Users/crcarter/.atom/packages/imdone-atom/lib/imdone-atom.coffee:83:35)
    at Object.module.exports.ImdoneAtom.tasks (/Users/crcarter/.atom/packages/imdone-atom/lib/imdone-atom.coffee:61:12)
    at atom-workspace.<anonymous> (/Users/crcarter/.atom/packages/imdone-atom/lib/imdone-atom.coffee:48:8)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:533:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:356:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:99:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -5:02.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -4:11.1.0 imdone-atom:tasks (atom-text-editor.editor.is-focused)
     -3:48.7.0 core:copy (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
     -3:47.4.0 application:open (atom-text-editor.editor.is-focused)
     -3:27.1.0 imdone-atom:tasks (atom-text-editor.editor.is-focused)
     -3:12.7.0 tabs:split-right (div.title.icon.icon-checklist)
     -2:31.5.0 imdone-atom:tasks (atom-text-editor.editor.is-focused)
     -2:23.4.0 application:new-file (div.package-detail.panels-item)
  5x -2:21.6.0 imdone-atom:tasks (atom-text-editor.editor.is-focused)
     -0:51.4.0 application:new-file (atom-text-editor.editor.is-focused)
  3x -0:50.1.0 imdone-atom:tasks (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ],
    "disabledPackages": [
      "open-on-github",
      "language-objective-c",
      "language-mustache",
      "language-make",
      "language-go",
      "language-gfm",
      "language-csharp",
      "language-clojure",
      "language-c",
      "language-python",
      "language-perl",
      "language-toml",
      "linter",
      "linter-php"
    ],
    "audioBeep": false,
    "ignoredNames": [
      ".git",
      ".DS_Store",
      "test/*",
      "node_modules"
    ]
  },
  "imdone-atom": {
    "openIn": {}
  }
}
```

### Installed Packages

```coffee
# User
Sublime-Style-Column-Selection, v1.3.0
color-picker, v2.0.14
emmet, v2.3.16
ever-notedown, v0.2.16
file-icons, v1.6.13
git-tab-status, v1.9.2
highlight-selected, v0.11.1
hyperclick, v0.0.35
imdone-atom, v1.3.3
minimap, v4.16.2
minimap-find-and-replace, v4.3.2
minimap-git-diff, v4.1.8
minimap-highlight-selected, v4.3.1
minimap-selection, v4.3.1
pain-split, v1.4.0
php-twig, v4.0.0
project-manager, v2.6.5
remote-sync, v3.5.0
symbol-gen, v1.0.0

# Dev
git-diff, v0.57.0
```

**Comment by piascikj** [comment]
I just published the fix for this in 1.3.4.  Thanks!
