### ISSUE TITLE
Uncaught ReferenceError: item is not defined

### ISSUE THREAD

**Issue by Braunson** [imdone/imdone-atom#56]
[Enter steps to reproduce below:]

1. Nothing, error just appeared.

**Atom Version**: 1.2.4
**System**: Microsoft Windows 8.1
**Thrown From**: [imdone-atom](https://github.com/imdone/imdone-atom) package, v1.3.4

### Stack Trace

Uncaught ReferenceError: item is not defined

```
At C:\Users\braunson\Dropbox\.atom\packages\imdone-atom\node_modules\imdone-core\node_modules\chokidar\index.js:261

ReferenceError: item is not defined
    at EventEmitter.FSWatcher._emitError (C:\Users\braunson\Dropbox\.atom\packages\imdone-atom\node_modules\imdone-core\node_modules\chokidar\index.js:261:15)
    at C:\Users\braunson\Dropbox\.atom\packages\imdone-atom\node_modules\imdone-core\node_modules\chokidar\index.js:298:39
    at FSReqWrap.oncomplete (fs.js:82:15)
```

### Commands

```
     -2:05.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  2x -2:04.8.0 core:move-up (atom-text-editor.editor.mini.is-focused)
  3x -2:03.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:59.3.0 core:copy (atom-text-editor.editor.is-focused)
     -1:59.1.0 core:close (atom-text-editor.editor.is-focused)
     -1:56.8.0 core:paste (atom-text-editor.editor.is-focused)
  5x -1:55.5.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:53.6.0 docblockr:parse-enter (atom-text-editor.editor.is-focused)
     -1:53.6.0 editor:newline (atom-text-editor.editor.is-focused)
  5x -1:52.4.0 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
     -1:50.7.0 core:move-up (atom-text-editor.editor.is-focused)
  6x -1:50.4.0 editor:move-to-end-of-word (atom-text-editor.editor.is-focused)
     -1:47.8.0 core:save (atom-text-editor.editor.is-focused)
     -1:46.1.0 docblockr:parse-enter (atom-text-editor.editor.is-focused)
     -1:46.1.0 editor:newline (atom-text-editor.editor.is-focused)
     -1:45.3.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true,
    "themes": [
      "one-dark-ui",
      "atom-light-syntax"
    ],
    "packagesWithKeymapsDisabled": [
      "imdone-atom"
    ],
    "disabledPackages": [
      "autocomplete-paths"
    ]
  },
  "imdone-atom": {}
}
```

### Installed Packages

```coffee
# User
aligner, v0.17.4
aligner-css, v1.2.0
aligner-php, v1.0.0
aligner-scss, v1.1.0
atom-beautify, vundefined
atom-shortcuts, v0.0.2
autocomplete-php, v0.3.7
color-picker, v2.0.14
devdocs, v0.2.1
docblockr, v0.7.3
editor-stats, v0.17.0
file-icons, v1.6.13
flex-tool-bar, v0.6.0
highlight-line, v0.11.0
highlight-selected, v0.11.1
imdone-atom, v1.3.4
imdone-atom-github, v0.1.7
jshint, v1.8.3
linter, v1.11.3
linter-php, v1.1.6
minimap, v4.16.2
minimap-bookmarks, v0.1.0
minimap-git-diff, v4.1.8
minimap-highlight-selected, v4.3.1
minimap-pigments, v0.1.7
php-cs-fixer, v2.5.1
pigments, vundefined
Remote-FTP, v0.7.14
tabs-to-spaces, v1.0.1
tool-bar, v0.1.9
tool-bar-main, v0.0.8
tree-view-git-modified, v0.6.0

# Dev
No dev packages
```

**Comment by piascikj** [comment]
Are you still getting this error?
