### ISSUE TITLE
Failed to activate the imdone-atom package

### ISSUE THREAD

**Issue by rwatts3** [imdone/imdone-atom#58]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.3.1
**System**: Mac OS X 10.11.2
**Thrown From**: [imdone-atom](https://github.com/imdone/imdone-atom) package, v1.3.11
### Stack Trace

Failed to activate the imdone-atom package

```
At Emitter has been disposed

Error: Emitter has been disposed
    at PluginViewInterface.module.exports.Emitter.on (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:38:15)
    at new Plugin (/Users/ryanwatts/.atom/packages/imdone-atom-github/lib/plugin.coffee:39:17)
    at ImdoneAtomView.module.exports.ImdoneAtomView.addPlugin (/Users/ryanwatts/.atom/packages/imdone-atom/lib/imdone-atom-view.coffee:221:20)
    at /Users/ryanwatts/.atom/packages/imdone-atom/lib/imdone-atom-view.coffee:184:10
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:86:11)
    at Object.module.exports.addPlugin (/Users/ryanwatts/.atom/packages/imdone-atom/lib/plugin-manager.coffee:11:14)
    at Object.module.exports.ImdoneAtomGithub.consumeImdone (/Users/ryanwatts/.atom/packages/imdone-atom-github/lib/imdone-atom-github.coffee:17:13)
    at Provider.module.exports.Provider.provide (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/service-hub/lib/provider.js:30:52)
    at ServiceHub.module.exports.ServiceHub.provide (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/service-hub/lib/service-hub.js:30:20)
    at Package.module.exports.Package.activateServices (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:330:71)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:173:16)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:150:32
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:143:26
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:140:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:517:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:444:29
    at exit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:73:16)
    at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:213:47)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:220:18
    at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:98:18)
    at emitOne (events.js:82:20)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
```
### Commands

```
     -2:36.7.0 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
     -2:35.6.0 docblockr:parse-enter (atom-text-editor.editor.is-focused)
     -2:35.6.0 editor:newline (atom-text-editor.editor.is-focused)
     -2:31.3.0 core:save (atom-text-editor.editor.is-focused.autocomplete-active)
  7x -2:30.9.0 core:move-down (atom-text-editor.editor.is-focused)
     -2:23.7.0 autocomplete-plus:cancel (atom-text-editor.editor.is-focused.autocomplete-active)
     -2:23 core:save (atom-text-editor.editor.is-focused)
  9x -2:22.5.0 core:move-left (atom-text-editor.editor.is-focused)
     -2:20.6.0 docblockr:parse-enter (atom-text-editor.editor.is-focused)
     -2:20.6.0 editor:newline (atom-text-editor.editor.is-focused)
     -2:20.2.0 core:move-up (atom-text-editor.editor.is-focused)
     -2:13.6.0 core:save (atom-text-editor.editor.is-focused)
     -1:46.1.0 imdone-atom:tasks (atom-text-editor.editor.is-focused)
     -1:43.1.0 core:close (div.imdone-atom.pane-item)
     -1:42.1.0 settings-view:open (atom-text-editor.editor.is-focused)
  2x -1:37 core:confirm (atom-text-editor.editor.mini.is-focused)
```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-material-ui",
      "peacocks-in-space-syntax"
    ],
    "disabledPackages": [
      "sync-settings"
    ],
    "followSymlinks": false,
    "packagesWithKeymapsDisabled": [
      "git-control",
      "imdone-atom"
    ]
  },
  "imdone-atom": {
    "openIn": {},
    "showNotifications": true
  }
}
```
### Installed Packages

``` coffee
# User
atom-material-ui, v0.8.0
docblockr, v0.7.3
imdone-atom, v1.3.11
imdone-atom-github, v0.1.7
jshint, v1.8.3
language-babel, v2.6.0
language-batch, v0.3.3
language-cfml, v0.10.0
language-latex, v0.6.1
language-nginx, v0.6.1
language-nunjucks, v2.0.0
linter, v1.11.3
linter-jsonlint, v1.1.2
markdown-preview, v0.157.0
meteor-api, v2.20.0
minimap, v4.18.0
pandoc-convert, v1.0.4
peacocks-in-space-syntax, v0.5.1
project-manager, v2.6.5
remote-edit, v1.8.23
term2, v0.9.21

# Dev
No dev packages
```

**Comment by piascikj** [comment]
Are you still getting this error?

**Comment by david0178418** [comment]
I just started getting it today.

[Enter steps to reproduce below:]

1. Start atom

**Atom Version**: 1.4.1
**System**: "Arch Linux"
**Thrown From**: [imdone-atom](https://github.com/imdone/imdone-atom) package, v1.3.25


### Stack Trace

Failed to activate the imdone-atom package

```
At Cannot find module 'atom-space-pen-views'

Error: Cannot find module 'atom-space-pen-views'
    at Module._resolveFilename (module.js:336:15)
    at Function.Module._resolveFilename (/usr/share/atom/resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/home/davidg/.atom/packages/imdone-atom/lib/imdone-atom-view.coffee:1:28)
    at Object.<anonymous> (/home/davidg/.atom/packages/imdone-atom/lib/imdone-atom-view.coffee:1:1)
    at Module._compile (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/usr/share/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/home/davidg/.atom/packages/imdone-atom/lib/imdone-atom.coffee:1:25)
    at Object.<anonymous> (/home/davidg/.atom/packages/imdone-atom/lib/imdone-atom.coffee:1:1)
    at Module._compile (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/usr/share/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/usr/share/atom/resources/app.asar/src/package.js:721:27)
    at Package.module.exports.Package.activateNow (/usr/share/atom/resources/app.asar/src/package.js:173:16)
    at /usr/share/atom/resources/app.asar/src/package.js:156:32
    at Package.module.exports.Package.measure (/usr/share/atom/resources/app.asar/src/package.js:92:15)
    at /usr/share/atom/resources/app.asar/src/package.js:149:26
    at Package.module.exports.Package.activate (/usr/share/atom/resources/app.asar/src/package.js:146:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/usr/share/atom/resources/app.asar/src/package-manager.js:524:21)
    at /usr/share/atom/resources/app.asar/src/package-manager.js:505:29
    at Config.module.exports.Config.transactAsync (/usr/share/atom/resources/app.asar/src/config.js:337:18)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true,
    "disabledPackages": [
      "jshint",
      "omnisharp-atom",
      "json-schema",
      "git-diff-details"
    ],
    "openEmptyEditorOnStart": false
  },
  "imdone-atom": {}
}
```

### Installed Packages

```coffee
# User
atom-yeoman, v0.3.15
autocomplete-paths, v1.0.2
imdone-atom, v1.3.25
language-babel, v2.15.2
linter, v1.11.3
linter-eslint, v6.0.0
minimap, v4.19.0
project-manager, v2.7.5
synced-sidebar, v0.4.3

# Dev
No dev packages
```

**Comment by piascikj** [comment]
Are either of you still having trouble activating the package?

**Comment by jneuendorf** [comment]
I get a similar error:

[Enter steps to reproduce below:]

1. Start atom

**Atom Version:** 1.14.1 x64
**System:** "macOS Sierra"
**Thrown From:** imdone-atom package, v2.1.18

### Stacktrace

```
Error: Cannot find module 'lodash'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.activate (/Users/jimneuendorf/.atom/packages/imdone-atom/lib/imdone-atom.coffee:94:9)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:218:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:190:32
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:96:15)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:183:26
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:180:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:550:34)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:531:29
    at Config.module.exports.Config.transactAsync (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:526:19)
    at PackageManager.module.exports.PackageManager.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:508:46)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:814:28
```

### Config

```coffee
core:
    audioBeep: false
    disabledPackages: [
        "spell-check"
        "welcome"
        "autocomplete-ruby"
    ]
    ignoredNames: [
        ".hg"
        ".svn"
        ".DS_Store"
        "._*"
        "Thumbs.db"
    ]
    themes: [
        "atom-material-ui"
        "atom-dark-syntax"
    ]
```

### Installed Packages

```
Community Packages (41) ~/.atom/packages
├── MagicPython@1.0.6
├── Sublime-Style-Column-Selection@1.7.3
├── atom-beautify@0.29.17
├── atom-material-syntax@1.0.2
├── atom-material-ui@1.3.9
├── autocomplete-paths@1.0.5
├── autocomplete-php@0.3.7
├── autocomplete-ruby@0.2.5
├── autocomplete-sass@0.1.0
├── block-comment@0.4.3
├── code-annotations@2.1.3
├── color-picker@2.2.5
├── dash@1.7.0
├── django-templates@0.5.0
├── emmet@2.4.3
├── export-html@3.1.0
├── file-icons@2.0.15
├── highlight-selected@0.12.0
├── html-entities@0.4.0
├── hyperclick@0.0.40
├── imdone-atom@2.1.18
├── js-hyperclick@1.10.1
├── language-latex@1.0.0
├── language-spacebars@0.2.2
├── linter@1.11.21
├── linter-coffeelint@1.2.1
├── linter-flake8@2.1.4
├── linter-htmlhint@1.3.1
├── linter-jshint@3.0.2
├── linter-php@1.3.1
├── linter-ruby@1.2.4
├── merge-conflicts@1.4.4
├── minimap@4.26.8
├── minimap-git-diff@4.3.1
├── minimap-highlight-selected@4.5.0
├── minimap-pigments@0.2.2
├── pdf-view@0.54.0
├── pigments@0.39.0
├── project-manager@3.3.3
├── sort-lines@0.14.0
└── tabs-to-spaces@1.0.3
```

**Comment by piascikj** [comment]
Is anyone still having this issue?

**Comment by nowarzz** [comment]
I am having issue and was brought here by Atom..

The stacktrace:
SyntaxError: Unexpected token ,
    at Module.get_Module._compile (C:\Users\no_wa\AppData\Local\atom\app-1.34.0\resources\app\static\<embedded>:11:146461)
    at Object.value [as .js] (C:\Users\no_wa\AppData\Local\atom\app-1.34.0\resources\app\static\<embedded>:11:150231)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (file:///C:/Users/no_wa/AppData/Local/atom/app-1.34.0/resources/app.asar/static/index.js:47:45)
    at require (C:\Users\no_wa\AppData\Local\atom\app-1.34.0\resources\app\static\<embedded>:11:145974)
    at Object.<anonymous> (C:\Users\no_wa\.atom\packages\imdone-atom\node_modules\keen-tracking\lib\server.js:7:24)
    at Object.<anonymous> (C:\Users\no_wa\.atom\packages\imdone-atom\node_modules\keen-tracking\lib\server.js:34:3)
    at Module.get_Module._compile (C:\Users\no_wa\AppData\Local\atom\app-1.34.0\resources\app\static\<embedded>:11:146684)
    at Object.value [as .js] (C:\Users\no_wa\AppData\Local\atom\app-1.34.0\resources\app\static\<embedded>:11:150231)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (file:///C:/Users/no_wa/AppData/Local/atom/app-1.34.0/resources/app.asar/static/index.js:47:45)
    at require (C:\Users\no_wa\AppData\Local\atom\app-1.34.0\resources\app\static\<embedded>:11:145974)
    at Object.<anonymous> (C:\Users\no_wa\.atom\packages\imdone-atom\lib\services\track.js:1:175)
    at Object.<anonymous> (C:\Users\no_wa\.atom\packages\imdone-atom\lib\services\track.js:23:3)
    at Module.get_Module._compile (C:\Users\no_wa\AppData\Local\atom\app-1.34.0\resources\app\static\<embedded>:11:146684)
    at Object.value [as .js] (C:\Users\no_wa\AppData\Local\atom\app-1.34.0\resources\app\static\<embedded>:11:150231)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (file:///C:/Users/no_wa/AppData/Local/atom/app-1.34.0/resources/app.asar/static/index.js:47:45)
    at require (C:\Users\no_wa\AppData\Local\atom\app-1.34.0\resources\app\static\<embedded>:11:145974)
    at Object.<anonymous> (file:///C:/Users/no_wa/.atom/packages/imdone-atom/lib/views/imdone-atom-view.coffee:3:9)
    at Object.<anonymous> (file:///C:/Users/no_wa/.atom/packages/imdone-atom/lib/views/imdone-atom-view.coffee:1:1)
    at Object.<anonymous> (file:///C:/Users/no_wa/.atom/packages/imdone-atom/lib/views/imdone-atom-view.coffee:1:1)
    at Module.get_Module._compile (C:\Users\no_wa\AppData\Local\atom\app-1.34.0\resources\app\static\<embedded>:11:146684)
    at Object.value [as .coffee] (C:\Users\no_wa\AppData\Local\atom\app-1.34.0\resources\app\static\<embedded>:11:150231)

**Comment by madeindjs** [comment]
Similar error. I just tried to install `imdone-atom` package with graphical menu.

**Atom**: 1.34.0 x64
**Electron**: 2.0.16
**OS**: Ubuntu 18.10
**Thrown From**: [imdone-atom](https://github.com/imdone/imdone-atom) package 2.4.31

### Stack Trace

Failed to activate the imdone-atom package

```
At Unexpected token ,

SyntaxError: Unexpected token ,
    at Module.get_Module._compile (/usr/share/atom/resources/app/static/<embedded>:11:146461)
    at Object.value [as .js] (/usr/share/atom/resources/app/static/<embedded>:11:150231)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (/usr/share/atom/resources/app/static/<embedded>:11:145974)
    at /packages/imdone-atom/node_modules/keen-tracking/lib/server.js:7:24)
    at /packages/imdone-atom/node_modules/keen-tracking/lib/server.js:34:3)
    at Module.get_Module._compile (/usr/share/atom/resources/app/static/<embedded>:11:146684)
    at Object.value [as .js] (/usr/share/atom/resources/app/static/<embedded>:11:150231)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (/usr/share/atom/resources/app/static/<embedded>:11:145974)
    at /packages/imdone-atom/lib/services/track.js:1:175)
    at /packages/imdone-atom/lib/services/track.js:23:3)
    at Module.get_Module._compile (/usr/share/atom/resources/app/static/<embedded>:11:146684)
    at Object.value [as .js] (/usr/share/atom/resources/app/static/<embedded>:11:150231)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (/usr/share/atom/resources/app/static/<embedded>:11:145974)
    at /packages/imdone-atom/lib/views/imdone-atom-view.coffee:3:9)
    at /packages/imdone-atom/lib/views/imdone-atom-view.coffee:1:1)
    at /packages/imdone-atom/lib/views/imdone-atom-view.coffee:1:1)
    at Module.get_Module._compile (/usr/share/atom/resources/app/static/<embedded>:11:146684)
    at Object.value [as .coffee] (/usr/share/atom/resources/app/static/<embedded>:11:150231)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (/usr/share/atom/resources/app/static/<embedded>:11:145974)
    at Object.activate (/packages/imdone-atom/lib/imdone-atom.coffee:106:23)
    at Package.activateNow (/usr/share/atom/resources/app/static/<embedded>:11:2921267)
    at measure (/usr/share/atom/resources/app/static/<embedded>:11:2920679)
    at Package.measure (/usr/share/atom/resources/app/static/<embedded>:11:2918310)
    at activationPromise.activationPromise.Promise (/usr/share/atom/resources/app/static/<embedded>:11:2920539)
    at new Promise (<anonymous>)
    at Package.activate (/usr/share/atom/resources/app/static/<embedded>:11:2920482)
    at PackageManager.activatePackage (/usr/share/atom/resources/app/static/<embedded>:11:382681)
    at /usr/share/atom/resources/app/static/<embedded>:11:917000
    at r (/usr/share/atom/resources/app/static/<embedded>:11:911606)
    at o (/usr/share/atom/resources/app/static/<embedded>:14:1037724)
    at t.bufferStream (/usr/share/atom/resources/app/static/<embedded>:14:1037878)
    at Socket.e.on (/usr/share/atom/resources/app/static/<embedded>:14:1036480)
    at emitOne (events.js:121:20)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:554:12)
```

### Commands

```
     -1:29.9.0 intentions:highlight (input.hidden-input)
     -1:29.9.0 settings-view:open (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
busy-signal 2.0.0 
docblockr 0.13.7 
emmet 2.4.3 
git-blame 1.8.0 
imdone-atom 2.4.31 
intentions 1.1.5 
language-apache 1.8.0 
language-asciidoc 1.11.0 
language-crystal-actual 0.37.2 
language-docker 1.1.8 
language-haml 0.32.1 
language-ini 1.20.0 
language-latex 1.2.0 
language-todotxt 1.1.5 
linter 2.3.0 
linter-php 1.6.0 
linter-ui-default 1.7.1 
```

**Comment by aubergine10** [comment]
Just run in to same issue:

[Enter steps to reproduce:]

1. Installed package
2. Error popped up

**Atom**: 1.35.1 x64
**Electron**: 2.0.18
**OS**: Microsoft Windows 10 Home
**Thrown From**: [imdone-atom](https://github.com/imdone/imdone-atom) package 2.4.31


### Stack Trace

Failed to activate the imdone-atom package

```
At Unexpected token ,

SyntaxError: Unexpected token ,
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.35.1/resources/app/static/<embedded>:11:146461)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.35.1/resources/app/static/<embedded>:11:150231)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.35.1/resources/app/static/<embedded>:11:145974)
    at /packages/imdone-atom/node_modules/keen-tracking/lib/server.js:7:24)
    at /packages/imdone-atom/node_modules/keen-tracking/lib/server.js:34:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.35.1/resources/app/static/<embedded>:11:146684)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.35.1/resources/app/static/<embedded>:11:150231)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.35.1/resources/app/static/<embedded>:11:145974)
    at /packages/imdone-atom/lib/services/track.js:1:175)
    at /packages/imdone-atom/lib/services/track.js:23:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.35.1/resources/app/static/<embedded>:11:146684)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.35.1/resources/app/static/<embedded>:11:150231)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.35.1/resources/app/static/<embedded>:11:145974)
    at /packages/imdone-atom/lib/views/imdone-atom-view.coffee:3:9)
    at /packages/imdone-atom/lib/views/imdone-atom-view.coffee:1:1)
    at /packages/imdone-atom/lib/views/imdone-atom-view.coffee:1:1)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.35.1/resources/app/static/<embedded>:11:146684)
    at Object.value [as .coffee] (~/AppData/Local/atom/app-1.35.1/resources/app/static/<embedded>:11:150231)
```

### Commands

```
```

### Non-Core Packages

```
behave-theme 1.7.0 
file-icons 2.1.31 
git-hide 1.0.0 
imdone-atom 2.4.31 
linter 2.3.0 
linter-eslint 8.5.2 
minimap 4.29.9 
minimap-find-and-replace 4.5.2 
minimap-git-diff 4.3.1 
minimap-lens 0.2.0 
minimap-linter 2.2.1 
minimap-selection 4.5.0 
minimap-titles 1.15.0 
nucleus-dark-ui 0.12.3 
pigments 0.40.2 
seti-ui 1.11.0 
```

Any known workarounds?

**Comment by SylvainGuieu** [comment]
Seems to be still there. 

1. ...
2. ...

**Atom**: 1.35.1 x64
**Electron**: 2.0.18
**OS**: Mac OS X 10.14.1
**Thrown From**: [imdone-atom](https://github.com/imdone/imdone-atom) package 2.4.31


### Stack Trace

Failed to activate the imdone-atom package

```
At Unexpected token ,

SyntaxError: Unexpected token ,
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146461)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:150231)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:145974)
    at /packages/imdone-atom/node_modules/keen-tracking/lib/server.js:7:24)
    at /packages/imdone-atom/node_modules/keen-tracking/lib/server.js:34:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146684)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:150231)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:145974)
    at /packages/imdone-atom/lib/services/track.js:1:175)
    at /packages/imdone-atom/lib/services/track.js:23:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146684)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:150231)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:145974)
    at /packages/imdone-atom/lib/views/imdone-atom-view.coffee:3:9)
    at /packages/imdone-atom/lib/views/imdone-atom-view.coffee:1:1)
    at /packages/imdone-atom/lib/views/imdone-atom-view.coffee:1:1)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146684)
    at Object.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:150231)
```

### Commands

```
```

### Non-Core Packages

```
advanced-open-file 0.16.8 
atom-html-preview 0.2.5 
atom-ide-debugger-python 0.7.3 
atom-ide-ui 0.13.0 
atom-material-syntax 1.0.8 
atom-material-ui 2.1.3 
atomic-emacs 0.12.1 
autocomplete-clang 0.11.5 
autocomplete-paths 2.12.2 
browser-plus 0.0.98 
build 0.70.0 
build-make 0.13.0 
busy-signal 1.4.3 
expand-region 0.4.0 
file-icons 2.1.26 
flatwhite-syntax 0.8.1 
git-plus 7.10.2 
git-time-machine 2.0.1 
hard-wrap 1.7.1 
Hydrogen 2.5.0 
ide-python 0.9.2 
imdone-atom 2.4.31 
intentions 1.1.5 
language-ini 1.20.0 
language-markdown 0.25.1 
language-matlab 0.2.1 
language-weave 0.4.3 
linter 2.2.0 
linter-gcc 0.7.1 
linter-ui-default 1.7.1 
markdown-preview-plus 3.1.1 
markdown-table-editor 1.1.0 
pane-manager 1.0.1 
pdf-view 0.70.0 
pen-paper-coffee-syntax 0.14.9 
platformio-ide 2.2.6 
platformio-ide-debugger 1.2.6 
platformio-ide-terminal 2.8.4 
python-debugger 0.2.0 
remember-file-positions 0.2.3 
script 3.18.1 
split-diff 1.4.0 
todo-show 2.3.0 
tool-bar 1.1.11 
```

**Comment by anoopmishra** [comment]
Enter steps to reproduce:

1. add the package 
2. start the atom app
3. you get in-app notification with this error.

**Atom**: 1.35.1 x64
**Electron**: 2.0.18
**OS**: Mac OS X 10.14.3
**Thrown From**: [imdone-atom](https://github.com/imdone/imdone-atom) package 2.4.31


### Stack Trace

Failed to activate the imdone-atom package

```
At Unexpected token ,

SyntaxError: Unexpected token ,
    at Module.get_Module._compile (/Applications/tools/Atom.app/Contents/Resources/app/static/<embedded>:11:146461)
    at Object.value [as .js] (/Applications/tools/Atom.app/Contents/Resources/app/static/<embedded>:11:150231)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (/Applications/tools/Atom.app/Contents/Resources/app/static/<embedded>:11:145974)
    at /packages/imdone-atom/node_modules/keen-tracking/lib/server.js:7:24)
    at /packages/imdone-atom/node_modules/keen-tracking/lib/server.js:34:3)
    at Module.get_Module._compile (/Applications/tools/Atom.app/Contents/Resources/app/static/<embedded>:11:146684)
    at Object.value [as .js] (/Applications/tools/Atom.app/Contents/Resources/app/static/<embedded>:11:150231)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (/Applications/tools/Atom.app/Contents/Resources/app/static/<embedded>:11:145974)
    at /packages/imdone-atom/lib/services/track.js:1:175)
    at /packages/imdone-atom/lib/services/track.js:23:3)
    at Module.get_Module._compile (/Applications/tools/Atom.app/Contents/Resources/app/static/<embedded>:11:146684)
    at Object.value [as .js] (/Applications/tools/Atom.app/Contents/Resources/app/static/<embedded>:11:150231)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (/Applications/tools/Atom.app/Contents/Resources/app/static/<embedded>:11:145974)
    at /packages/imdone-atom/lib/views/imdone-atom-view.coffee:3:9)
    at /packages/imdone-atom/lib/views/imdone-atom-view.coffee:1:1)
    at /packages/imdone-atom/lib/views/imdone-atom-view.coffee:1:1)
    at Module.get_Module._compile (/Applications/tools/Atom.app/Contents/Resources/app/static/<embedded>:11:146684)
    at Object.value [as .coffee] (/Applications/tools/Atom.app/Contents/Resources/app/static/<embedded>:11:150231)
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.33.4 
goto-definition 1.3.4 
Hydrogen 2.8.0 
imdone-atom 2.4.31 
nuclide 0.366.0 
pdf-view 0.71.0 
svg-preview 0.14.0 
```

**Comment by diveyez** [comment]
4 YEARS AND NO PULL TO FIX?

**Comment by ldahl264** [comment]
Also running into this and was brought here from the notice.

**Comment by piascikj** [comment]
This is fixed in 2.4.32.  It will be my last contribution to imdone-atom.

**Comment by piascikj** [comment]
@ldahl264 @diveyez Wanna give the latest a try?

**Comment by aubergine10** [comment]
Just tested, seems to work.
