### ISSUE TITLE
Uncaught Error: EBUSY: resource busy or locked, read

### ISSUE THREAD

**Issue by Off76** [imdone/imdone-atom#69]
Hi,

I have some problems with your plugin, it keep crashing atom when I try to access to the todo page ( using alt+t )

Here is the report.

**Atom Version**: 1.3.3
**System**: Windows 7 64
**Thrown From**: [imdone-atom](https://github.com/imdone/imdone-atom) package, v1.3.19

### Stack Trace

Uncaught Error: EBUSY: resource busy or locked, read

```
At fs.js:603

Error: EBUSY: resource busy or locked, read
    at Error (native)
    at Object.fs.readSync (fs.js:603:19)
    at Object.fs.readFileSync (fs.js:438:24)
    at Object.fs.readFileSync (ATOM_SHELL_ASAR.js:385:29)
    at File.module.exports.File.readSync (C:\Users\a.user\AppData\Local\atom\app-1.3.3\resources\app.asar\node_modules\pathwatcher\lib\file.js:266:36)
    at File.module.exports.File.getDigestSync (C:\Users\a.user\AppData\Local\atom\app-1.3.3\resources\app.asar\node_modules\pathwatcher\lib\file.js:167:14)
    at Watcher.isReallyChanged (file:///C:/Users/a.user/.atom/packages/imdone-atom/lib/atom-watched-fs-store.coffee:72:19)
    at Watcher.fileAdded (file:///C:/Users/a.user/.atom/packages/imdone-atom/lib/atom-watched-fs-store.coffee:149:20)
    at Watcher.watchFile (file:///C:/Users/a.user/.atom/packages/imdone-atom/lib/atom-watched-fs-store.coffee:98:8)
    at Watcher.watchDir (file:///C:/Users/a.user/.atom/packages/imdone-atom/lib/atom-watched-fs-store.coffee:93:6)
    at Watcher.watchDir (file:///C:/Users/a.user/.atom/packages/imdone-atom/lib/atom-watched-fs-store.coffee:92:6)
    at Watcher.watchDir (file:///C:/Users/a.user/.atom/packages/imdone-atom/lib/atom-watched-fs-store.coffee:92:6)
    at Watcher.watchDir (file:///C:/Users/a.user/.atom/packages/imdone-atom/lib/atom-watched-fs-store.coffee:92:6)
    at Watcher.watchDir (file:///C:/Users/a.user/.atom/packages/imdone-atom/lib/atom-watched-fs-store.coffee:92:6)
    at Watcher.watchDir (file:///C:/Users/a.user/.atom/packages/imdone-atom/lib/atom-watched-fs-store.coffee:92:6)
    at new Watcher (file:///C:/Users/a.user/.atom/packages/imdone-atom/lib/atom-watched-fs-store.coffee:44:6)
    at Repository.repo.initWatcher (file:///C:/Users/a.user/.atom/packages/imdone-atom/lib/atom-watched-fs-store.coffee:193:24)
    at file:///C:/Users/a.user/.atom/packages/imdone-atom/lib/atom-watched-fs-store.coffee:177:12
    at C:\Users\a.user\.atom\packages\imdone-atom\node_modules\imdone-core\lib\mixins\repo-fs-store.js:59:11
    at C:\Users\a.user\.atom\packages\imdone-atom\node_modules\imdone-core\node_modules\async\lib\async.js:726:13
    at C:\Users\a.user\.atom\packages\imdone-atom\node_modules\imdone-core\node_modules\async\lib\async.js:52:16
    at replenish (C:\Users\a.user\.atom\packages\imdone-atom\node_modules\imdone-core\node_modules\async\lib\async.js:306:28)
    at C:\Users\a.user\.atom\packages\imdone-atom\node_modules\imdone-core\node_modules\async\lib\async.js:326:29
    at C:\Users\a.user\.atom\packages\imdone-atom\node_modules\imdone-core\node_modules\async\lib\async.js:44:16
    at C:\Users\a.user\.atom\packages\imdone-atom\node_modules\imdone-core\node_modules\async\lib\async.js:723:17
    at C:\Users\a.user\.atom\packages\imdone-atom\node_modules\imdone-core\node_modules\async\lib\async.js:167:37
    at C:\Users\a.user\.atom\packages\imdone-atom\node_modules\imdone-core\lib\repository.js:657:11
    at C:\Users\a.user\.atom\packages\imdone-atom\node_modules\imdone-core\lib\repository.js:624:9
    at C:\Users\a.user\.atom\packages\imdone-atom\node_modules\imdone-core\lib\repository.js:463:5
    at C:\Users\a.user\.atom\packages\imdone-atom\node_modules\imdone-core\lib\mixins\repo-fs-store.js:104:11
```

### Commands

```
     -0:55 imdone-atom:tasks (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {},
  "imdone-atom": {
    "openIn": {},
    "todaysJournal": {}
  }
}
```

### Installed Packages

```coffee
# User
docs-snippets, v0.8.0
file-icons, v1.6.13
imdone-atom, v1.3.19
keyboard-localization, v1.4.13
linter, v1.11.3
linter-eslint, v5.2.7
minimap, v4.19.0

# Dev
No dev packages
```

**Comment by piascikj** [comment]
I put a try/catch in the digest check, so this should work now.  I'm not sure what the cause is though.  It seems like there's a file locked for read.  If you run into any more issues related to this I can walk you through a debug session to see what's going on.

**Comment by Off76** [comment]
I have upgraded the plugin to the latest version but it keep crashing Atom when I try to access to the todo page.
Actually it freeze on loading, at the screen saying "Loading [project] Tasks. It's gonna be legen... wait for it. Found 102 files in [project] Tasks".
Then Atom is saying "Editor is not responding".

I know that there is a file deletion problem on the actual version of Atom on Windows 7 ( https://github.com/atom/tree-view/issues/666 )  so maybe it's related somehow, I didn't look at your plugin source code for now but I could check and try to debug the issue.

**Comment by piascikj** [comment]
@Off76 Are you still receiving this error?

**Comment by Off76** [comment]
@piascikj No it's seems working now, thanks.

So you find why there was an error ?

**Comment by piascikj** [comment]
I went back to the more tried and true file watching library and it cleared it up.  I was never able to reproduce the error.
