### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory

### ISSUE THREAD

**Issue by burgerzzz** [imdone/imdone-atom#76]
I'm getting this error as soon as I attempt to launch a task-board for my project, directly after a fresh install, so this hasn't worked for me at all.

**Atom Version**: 1.4.3
**System**: Mac OS X 10.11.3
**Thrown From**: [imdone-atom](https://github.com/imdone/imdone-atom) package, v1.3.25

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, open '/Users/steven/Documents/Developd/developd-business-client/node_modules/asar/test/expected/packthis-unpack-dir.asar.unpacked/dir2/file3.txt'

```
At fs.js:549

Error: ENOENT: no such file or directory, open '/Users/steven/Documents/Developd/developd-business-client/node_modules/asar/test/expected/packthis-unpack-dir.asar.unpacked/dir2/file3.txt'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:148:18)
    at Function.module.exports.sync (/Users/steven/.atom/packages/imdone-atom/node_modules/imdone-core/node_modules/read-chunk/index.js:34:14)
    at /Users/steven/.atom/packages/imdone-atom/node_modules/imdone-core/lib/mixins/repo-fs-store.js:104:31
    at ATOM_SHELL_ASAR.js:217:16
    at doNTCallback0 (node.js:419:9)
    at process._tickCallback (node.js:348:13)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "remote-edit"
    ],
    "themes": [
      "one-dark-ui",
      "oceanic-next"
    ]
  },
  "imdone-atom": {
    "openIn": {},
    "todaysJournal": {}
  }
}
```

### Installed Packages

```coffee
# User
color-picker, v2.1.1
imdone-atom, v1.3.25
language-javascript-jsx, v0.3.7
linter, v1.11.3
linter-eslint, v6.0.0
linter-htmlhint, v1.0.2
linter-less, v2.4.0
linter-scss-lint, v2.5.1
minimap, v4.19.0
oceanic-next, v0.1.2
project-manager, v2.7.5
react, v0.14.1
react-es6-snippets, v0.3.0

# Dev
No dev packages
```

**Comment by piascikj** [comment]
Is this still an issue?
