### ISSUE TITLE
Uncaught RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by ThatTomPerson** [imdone/imdone-atom#78]
Had a project that has "1826 files in [name] Tasks"

**Atom Version**: 1.5.3
**System**: Mac OS X 10.11.3
**Thrown From**: [imdone-atom](https://github.com/imdone/imdone-atom) package, v1.3.27
### Stack Trace

Uncaught RangeError: Maximum call stack size exceeded

```
At /Users/thattomperson/.atom/packages/imdone-atom/node_modules/imdone-core/lib/file.js:363

RangeError: Maximum call stack size exceeded
    at RegExp.exec (native)
    at File.extractLinkStyleTasks (/Users/thattomperson/.atom/packages/imdone-atom/node_modules/imdone-core/lib/file.js:363:34)
    at File.extractTasksInNonCodeFile (/Users/thattomperson/.atom/packages/imdone-atom/node_modules/imdone-core/lib/file.js:395:8)
    at File.extractTasks (/Users/thattomperson/.atom/packages/imdone-atom/node_modules/imdone-core/lib/file.js:543:10)
    at extract (/Users/thattomperson/.atom/packages/imdone-atom/node_modules/imdone-core/lib/repository.js:528:10)
    at Repository.extractTasks (/Users/thattomperson/.atom/packages/imdone-atom/node_modules/imdone-core/lib/repository.js:539:10)
    at /Users/thattomperson/.atom/packages/imdone-atom/node_modules/imdone-core/lib/repository.js:618:12
    at /Users/thattomperson/.atom/packages/imdone-atom/node_modules/imdone-core/lib/mixins/repo-fs-store.js:366:9
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)
```
### Commands

```
     -1:20.4.0 core:close (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -1:06.3.0 find-and-replace:show (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
  2x -1:05.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -1:02.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:02.5.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -1:01.1.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -1:01.1.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:38.3.0 core:save (atom-text-editor.editor.vim-mode.insert-mode.is-focused.autocomplete-active)
  2x -0:33.6.0 settings-view:open (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -0:30.2.0 core:close (div.package-detail.panels-item)
     -0:29.5.0 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -0:28.2.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:28.2.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:27.6.0 imdone-atom:tasks (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -0:05.0 core:close (div.imdone-atom.pane-item)
     -0:03.5.0 imdone-atom:tasks (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "language-todo"
    ],
    "themes": [
      "atom-material-ui",
      "atom-material-syntax"
    ]
  },
  "imdone-atom": {
    "openIn": {},
    "showNotifications": true,
    "showTagsInline": true,
    "todaysJournal": {}
  }
}
```
### Installed Packages

``` coffee
# User
atom-material-syntax, v0.4.3
atom-material-ui, v1.2.0
docblockr, v0.7.3
editorconfig, v1.2.4
git-control, v0.4.0
imdone-atom, v1.3.27
language-lua, v0.9.4
language-vue-component, v0.4.4
linter, v1.11.3
linter-eslint, v7.0.0
pigments, v0.24.2
vim-mode, v0.64.0

# Dev
No dev packages
```

**Comment by BispensGipsGebis** [comment]
Any known workarounds or fixes for this issue? Blocks the package completely

**Comment by kofronpi** [comment]
I have the same issue and it makes atom crash.

**Comment by praveendhawan** [comment]
+1

**Comment by ayoubelabbassi** [comment]
same here

**Comment by kinged007** [comment]
Same here and only found 156 files ! :( 
+1

**Comment by piascikj** [comment]
Anyone experiencing the range error please try 2.1.20 and let me know if you're still experiencing the issue.  If you are, please attach a fresh stack trace.

**Comment by kinged007** [comment]
Hi, I am still receiving the error.

`/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:699
Hide Stack Trace
RangeError: Maximum call stack size exceeded
    at Config.module.exports.Config.deepClone (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:699:11)
    at Config.module.exports.Config.deepDefaults (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:719:27)
    at Config.module.exports.Config.deepDefaults (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:715:32)
    at Config.module.exports.Config.getRawValue (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:588:16)
    at Config.module.exports.Config.get (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:181:21)
    at Object.getSettings (/Users/joshua/.atom/packages/imdone-atom/lib/services/imdone-config.coffee:9:34)
    at Repository.imdoneRepo.shouldExclude (/Users/joshua/.atom/packages/imdone-atom/lib/services/imdone-helper.coffee:30:74)
    at Repository.repo.fileOK (/Users/joshua/.atom/packages/imdone-atom/node_modules/imdone-core/lib/mixins/repo-fs-store.js:105:14)
    at /Users/joshua/.atom/packages/imdone-atom/node_modules/imdone-core/lib/mixins/repo-fs-store.js:250:14
    at /Users/joshua/.atom/packages/imdone-atom/node_modules/async/lib/async.js:181:20
    at replenish (/Users/joshua/.atom/packages/imdone-atom/node_modules/async/lib/async.js:319:21)
    at /Users/joshua/.atom/packages/imdone-atom/node_modules/async/lib/async.js:326:29
    at /Users/joshua/.atom/packages/imdone-atom/node_modules/async/lib/async.js:44:16
    at /Users/joshua/.atom/packages/imdone-atom/node_modules/imdone-core/lib/mixins/repo-fs-store.js:270:11
    at Repository.repo.fileOK (/Users/joshua/.atom/packages/imdone-atom/node_modules/imdone-core/lib/mixins/repo-fs-store.js:105:42)
    at /Users/joshua/.atom/packages/imdone-atom/node_modules/imdone-core/lib/mixins/repo-fs-store.js:250:14
    at /Users/joshua/.atom/packages/imdone-atom/node_modules/async/lib/async.js:181:20
    at replenish (/Users/joshua/.atom/packages/imdone-atom/node_modules/async/lib/async.js:319:21)
    at /Users/joshua/.atom/packages/imdone-atom/node_modules/async/lib/async.js:326:29
    at /Users/joshua/.atom/packages/imdone-atom/node_modules/async/lib/async.js:44:16
    at /Users/joshua/.atom/packages/imdone-atom/node_modules/imdone-core/lib/mixins/repo-fs-store.js:270:11
    at Repository.repo.fileOK (/Users/joshua/.atom/packages/imdone-atom/node_modules/imdone-core/lib/mixins/repo-fs-store.js:105:42)
    at /Users/joshua/.atom/packages/imdone-atom/node_modules/imdone-core/lib/mixins/repo-fs-store.js:250:14
    at /Users/joshua/.atom/packages/imdone-atom/node_modules/async/lib/async.js:181:20
    at replenish (/Users/joshua/.atom/packages/imdone-atom/node_modules/async/lib/async.js:319:21)
    at /Users/joshua/.atom/packages/imdone-atom/node_modules/async/lib/async.js:326:29
    at /Users/joshua/.atom/packages/imdone-atom/node_modules/async/lib/async.js:44:16
    at /Users/joshua/.atom/packages/imdone-atom/node_modules/imdone-core/lib/mixins/repo-fs-store.js:270:11
    at Repository.repo.fileOK (/Users/joshua/.atom/packages/imdone-atom/node_modules/imdone-core/lib/mixins/repo-fs-store.js:105:42)
    at /Users/joshua/.atom/packages/imdone-atom/node_modules/imdone-core/lib/mixins/repo-fs-store.js:250:14
    at /Users/joshua/.atom/packages/imdone-atom/node_modules/async/lib/async.js:181:20
    at replenish (/Users/joshua/.atom/packages/imdone-atom/node_modules/async/lib/async.js:319:21)
    at /Users/joshua/.atom/packages/imdone-atom/node_modules/async/lib/async.js:326:29
    at /Users/joshua/.atom/packages/imdone-atom/node_modules/async/lib/async.js:44:16
    at /Users/joshua/.atom/packages/imdone-atom/node_modules/imdone-core/lib/mixins/repo-fs-store.js:270:11
    at Repository.repo.fileOK (/Users/joshua/.atom/packages/imdone-atom/node_modules/imdone-core/lib/mixins/repo-fs-store.js:105:42)`

**Comment by praveendhawan** [comment]
I am still receiving the error. The stack trace is pretty big. Please have a look at this link to see the stack trace - > [Link for Error Stack trace](https://gist.github.com/praveendhawan/7b4233276b9f78882843523fb8f63e26)

**Comment by piascikj** [comment]
@praveendhawan @kinged007 Try v2.1.21.  I filtered the files before calling async.each.  I think it's fixed.

**Comment by kinged007** [comment]
Its Working!! ! :D Thank you! You are awesome!
ᐧ

**Comment by piascikj** [comment]
WOOT!!!
