### ISSUE TITLE
Uncaught Error: EBADF: bad file descriptor, read

### ISSUE THREAD

**Issue by netrc** [imdone/imdone-atom#89]
[Enter steps to reproduce below:]

1. ... Saved a file. 
2. ...

**Atom Version**: 1.7.2
**System**: Microsoft Windows 7 Professional 
**Thrown From**: [imdone-atom](https://github.com/imdone/imdone-atom) package, v1.3.29

### Stack Trace

Uncaught Error: EBADF: bad file descriptor, read

```
At fs.js:651

Error: EBADF: bad file descriptor, read
    at Error (native)
    at Object.fs.readSync (fs.js:651:19)
    at Function.module.exports.sync (C:\Users\ricampbe\.atom\packages\imdone-atom\node_modules\imdone-core\node_modules\read-chunk\index.js:35:21)
    at C:\Users\ricampbe\.atom\packages\imdone-atom\node_modules\imdone-core\lib\mixins\repo-fs-store.js:104:31
    at FSReqWrap.oncomplete (fs.js:82:15)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-light-ui",
      "solarized-light-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
git-plus, v5.13.4
imdone-atom, v1.3.29

# Dev
No dev packages
```

**Comment by piascikj** [comment]
Is this still an issue?
