### ISSUE TITLE
Error: EBUSY: resource busy or locked, open 'C:\Users\PICCO_3\AppData\Local\Temp\shelljs_069fa2634a687e057277'

### ISSUE THREAD

**Issue by Giriprasaths** [imdone/imdone-atom#90]
If run the ionic serve command in the command prompt, i got the following error, so i cannot test my ionic app in the browser.

E:\mobileApp\project\wpIonicAppv1.1>ionic serve
shell.js: internal error
Error: EBUSY: resource busy or locked, open 'C:\Users\PICCO_3\AppData\Local\Temp\shelljs_069fa2634a687e057277'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.writeFileSync (fs.js:1156:15)
    at execSync (C:\Users\PICCO_3\AppData\Roaming\npm\node_modules\ionic\node_modules\shelljs\src\exec.js:67:57)
    at Object._exec (C:\Users\PICCO_3\AppData\Roaming\npm\node_modules\ionic\node_modules\shelljs\src\exec.js:179:12)
    at Object.exec (C:\Users\PICCO_3\AppData\Roaming\npm\node_modules\ionic\node_modules\shelljs\src\common.js:168:23)
    at Object.gulpInstalledGlobally (C:\Users\PICCO_3\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\lib\utils.js:301:24)
    at Object.gulpStartupTasks (C:\Users\PICCO_3\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\lib\serve.js:277:15)
    at C:\Users\PICCO_3\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\lib\serve.js:526:38
    at _fulfilled (C:\Users\PICCO_3\AppData\Roaming\npm\node_modules\ionic\node_modules\q\q.js:787:54)

**Comment by Keshar9841** [comment]
why has this still not been answered?? I am also getting the same kind of error.

**Comment by piascikj** [comment]
I assume this is under windows?  What version of windows, and what directory are you running imdone-atom from?

**Comment by pledges** [comment]
I'm also experiencing the same problem. And yes I'm on Windows 7.

**Comment by piascikj** [comment]
What is the path to the project you are opening imdone-atom on?

**Comment by pledges** [comment]
I did a system reboot and problem was fix.

**Comment by ominfowave** [comment]
i have same problem please give me solution

**Comment by nicolauses** [comment]
i have the same proplem. I was update my Ionic version to version 2Beta, and one day after i got this kind of problem, i tried to update the nodeJS, the npm, etc, but it doesn't work.

**Comment by piascikj** [comment]
Try adding the path of the file it's seeing as BUSY to .imdoneignore

**Comment by piascikj** [comment]
Is anyone still having this issue?

**Comment by soujanyaui** [comment]
yes i am having a same issue and i am using windows 10 and and npm version is 5.6.0 and node verison is v6.9.0 


                                                                                                                                                                                  
fs.js:1089                                                                                                                                                                        
  return binding.unlink(pathModule._makeLong(path));                                                                                                                              
                 ^                                                                                                                                                                
                                                                                                                                                                                  
Error: EBUSY: resource busy or locked, unlink 'C:\laragon\www\tradenavigator\public\images\reversalboxIslan.png'                                                                  
    at Error (native)                                                                                                                                                             
    at Object.fs.unlinkSync (fs.js:1089:18)                                                                                                                                       
    at copyFileSync (C:\laragon\www\tradenavigator\node_modules\fs-extra\lib\copy-sync\copy-file-sync.js:15:10)                                                                   
    at copySync (C:\laragon\www\tradenavigator\node_modules\fs-extra\lib\copy-sync\copy-sync.js:43:5)                                                                             
    at contents.forEach.content (C:\laragon\www\tradenavigator\node_modules\fs-extra\lib\copy-sync\copy-sync.js:54:7)                                                             
    at Array.forEach (native)                                                                                                                                                     
    at Object.copySync (C:\laragon\www\tradenavigator\node_modules\fs-extra\lib\copy-sync\copy-sync.js:51:14)                                                                     
    at File.copyTo (C:\laragon\www\tradenavigator\node_modules\laravel-mix\src\File.js:210:12)                                                                                    
    at FileCollection.copyTo (C:\laragon\www\tradenavigator\node_modules\laravel-mix\src\FileCollection.js:88:24)                                                                 
    at src.forEach.file (C:\laragon\www\tradenavigator\node_modules\laravel-mix\src\FileCollection.js:82:38)                                                                      
    at Array.forEach (native)                                                                                                                                                     
    at FileCollection.copyTo (C:\laragon\www\tradenavigator\node_modules\laravel-mix\src\FileCollection.js:82:17)                                                                 
    at CopyFilesTask.run (C:\laragon\www\tradenavigator\node_modules\laravel-mix\src\tasks\CopyFilesTask.js:14:20)                                                                
    at CustomTasksPlugin.runTask (C:\laragon\www\tradenavigator\node_modules\laravel-mix\src\plugins\CustomTasksPlugin.js:34:14)                                                  
    at Mix.tasks.forEach.task (C:\laragon\www\tradenavigator\node_modules\laravel-mix\src\plugins\CustomTasksPlugin.js:9:44)                                                      
    at Array.forEach (native)                                                                                                                                                     
    at Compiler.compiler.plugin.stats (C:\laragon\www\tradenavigator\node_modules\laravel-mix\src\plugins\CustomTasksPlugin.js:9:23)                                              
    at Compiler.applyPlugins (C:\laragon\www\tradenavigator\node_modules\tapable\lib\Tapable.js:61:14)                                                                            
    at emitRecords.err (C:\laragon\www\tradenavigator\node_modules\webpack\lib\Compiler.js:264:11)                                                                                
    at Compiler.emitRecords (C:\laragon\www\tradenavigator\node_modules\webpack\lib\Compiler.js:371:38)                                                                           
    at emitAssets.err (C:\laragon\www\tradenavigator\node_modules\webpack\lib\Compiler.js:258:10)                                                                                 
    at applyPluginsAsyncSeries1.err (C:\laragon\www\tradenavigator\node_modules\webpack\lib\Compiler.js:364:12)                                                                   
    at next (C:\laragon\www\tradenavigator\node_modules\tapable\lib\Tapable.js:218:11)                                                                                            
    at Compiler.compiler.plugin (C:\laragon\www\tradenavigator\node_modules\webpack\lib\performance\SizeLimitsPlugin.js:99:4)                                                     
    at Compiler.applyPluginsAsyncSeries1 (C:\laragon\www\tradenavigator\node_modules\tapable\lib\Tapable.js:222:13)                                                               
    at Compiler.afterEmit (C:\laragon\www\tradenavigator\node_modules\webpack\lib\Compiler.js:361:9)                                                                              
    at require.forEach.err (C:\laragon\www\tradenavigator\node_modules\webpack\lib\Compiler.js:350:15)                                                                            
    at C:\laragon\www\tradenavigator\node_modules\async\dist\async.js:473:16                                                                                                      
    at iteratorCallback (C:\laragon\www\tradenavigator\node_modules\async\dist\async.js:1050:13)                                                                                  
    at C:\laragon\www\tradenavigator\node_modules\async\dist\async.js:958:16                                                                                                      
npm ERR! code ELIFECYCLE                                                                                                                                                          
npm ERR! errno 1                                                                                                                                                                  
npm ERR! @ development: `cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`  
npm ERR! Exit status 1                                                                                                                                                            
npm ERR!                                                                                                                                                                          
npm ERR! Failed at the @ development script.                                                                                                                                      
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.                                                                                
                                                                                                                                                                                  
npm ERR! A complete log of this run can be found in:                                                                                                                              
npm ERR!     C:\Users\sxp\AppData\Roaming\npm-cache\_logs\2018-02-27T16_17_29_716Z-debug.log                                                                                      
npm ERR! code ELIFECYCLE                                                                                                                                                          
npm ERR! errno 1                                                                                                                                                                  
npm ERR! @ dev: `npm run development`                                                                                                                                             
npm ERR! Exit status 1                                                                                                                                                            
npm ERR!                                                                                                                                                                          
npm ERR! Failed at the @ dev script.                                                                                                                                              
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.                                                                                
                                                                                                                                                                                  
npm ERR! A complete log of this run can be found in:                                                                                                                              
npm ERR!     C:\Users\sxp\AppData\Roaming\npm-cache\_logs\2018-02-27T16_17_30_151Z-debug.log   

let me know if anyone found how to fix this issue thanks in advance !
