### ISSUE TITLE
Uncaught Error: EBUSY: resource busy or locked, open 'C:\Users\Emklos\ntuser.dat.LOG1'

### ISSUE THREAD

**Issue by MaciejKlosowski** [imdone/imdone-atom#98]
Hi All,
1. I installed the plugin.
2. When I tried to open tasks the following errors appeared:

**Atom Version**: 1.7.3
**System**: Microsoft Windows 10 Pro
**Thrown From**: [imdone-atom](https://github.com/imdone/imdone-atom) package, v1.3.29
### Stack Trace

Uncaught Error: EBUSY: resource busy or locked, open 'C:\Users\Emklos\ntuser.dat.LOG1'

```
At fs.js:584

Error: EBUSY: resource busy or locked, open 'C:\Users\Emklos\ntuser.dat.LOG1'
    at Error (native)
    at Object.fs.openSync (fs.js:584:18)
    at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:159:20)
    at Function.module.exports.sync (C:\Users\Emklos\.atom\packages\imdone-atom\node_modules\imdone-core\node_modules\read-chunk\index.js:34:14)
    at C:\Users\Emklos\.atom\packages\imdone-atom\node_modules\imdone-core\lib\mixins\repo-fs-store.js:104:31
    at FSReqWrap.oncomplete (fs.js:82:15)
```
### Commands

```
     -1:29.1.0 imdone-atom:todays-journal (atom-text-editor.editor.mini.is-focused)
     -1:27.5.0 imdone-atom:tasks (atom-text-editor.editor.is-focused.power-mode)
     -0:34.9.0 imdone-atom:todays-journal (atom-text-editor.editor.power-mode.is-focused)
     -0:32.8.0 imdone-atom:tasks (atom-text-editor.editor.power-mode.is-focused)
  3x -0:20.4.0 core:backspace (atom-text-editor.editor.power-mode.is-focused)
     -0:17 editor:newline (atom-text-editor.editor.power-mode.is-focused)
  3x -0:16.4.0 core:backspace (atom-text-editor.editor.power-mode.is-focused)
     -0:15.4.0 editor:newline (atom-text-editor.editor.power-mode.is-focused)
     -0:12.5.0 imdone-atom:tasks (atom-text-editor.editor.power-mode.is-focused)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "linter-write-good"
    ]
  },
  "imdone-atom": {
    "showNotifications": true,
    "showTagsInline": true,
    "todaysJournal": {
      "dateFormat": "DD-MM-YYYY",
      "monthFormat": "MM-YYYY"
    }
  }
}
```
### Installed Packages

``` coffee
# User
activate-power-mode, v0.5.2
imdone-atom, v1.3.29
linter, v1.11.4
linter-alex, v3.0.0
linter-proselint, v3.0.1
minimap, v4.24.0
project-manager, v2.9.7

# Dev
No dev packages
```

**Comment by piascikj** [comment]
This happens because a file is not able to be accessed.  I'll fix the handling of the exception in the next release.  Did you intend for imdone to look at your entire home folder?  My guess is no, but if you did, do you need it to look at `ntuser.dat.LOG1`?  If not, then add an [.imdoneignore file](https://github.com/imdone/imdone-atom#ignoring-files).

**Comment by piascikj** [comment]
Is this still an issue?
