### ISSUE TITLE
Uncaught TypeError: Cannot read property 'options' of null

### ISSUE THREAD

**Issue by onetrev** [imdone/imdone-atom#99]
STEPS TO REPRODUCE:
1. I just tried to drag and drop some items in Imdone and this happened.
2. But on reload it works fine. Maybe a one off? I can just close this issue if you think so.

**Atom Version**: 1.7.4
**System**: Microsoft Windows 10 Home
**Thrown From**: [imdone-atom](https://github.com/imdone/imdone-atom) package, v1.3.29
### Stack Trace

Uncaught TypeError: Cannot read property 'options' of null

```
At C:\Users\Trevor\.atom\packages\imdone-atom\node_modules\sortablejs\Sortable.js:1104

TypeError: Cannot read property 'options' of null
    at _onMove (C:\Users\Trevor\.atom\packages\imdone-atom\node_modules\sortablejs\Sortable.js:1104:23)
    at Sortable._onDragOver (C:\Users\Trevor\.atom\packages\imdone-atom\node_modules\sortablejs\Sortable.js:653:20)
    at Sortable.handleEvent (C:\Users\Trevor\.atom\packages\imdone-atom\node_modules\sortablejs\Sortable.js:842:11)
```
### Commands

```
     -9:37.6.0 core:close (atom-text-editor.editor.is-focused)
     -9:15.3.0 core:backspace (atom-text-editor.editor.is-focused)
     -9:13.7.0 core:cut (atom-text-editor.editor.is-focused)
  2x -9:13.3.0 core:backspace (atom-text-editor.editor.is-focused)
     -9:11.8.0 docblockr:parse-enter (atom-text-editor.editor.is-focused)
  3x -9:11.2.0 core:backspace (atom-text-editor.editor.is-focused)
     -9:09.6.0 core:paste (atom-text-editor.editor.is-focused)
 23x -9:08.9.0 core:move-left (atom-text-editor.editor.is-focused)
  2x -9:06.6.0 core:move-up (atom-text-editor.editor.is-focused)
  3x -9:05.9.0 core:move-down (atom-text-editor.editor.is-focused)
     -9:04.5.0 core:move-up (atom-text-editor.editor.is-focused)
  5x -9:00.0 core:backspace (atom-text-editor.editor.is-focused)
 11x -8:56.1.0 core:move-right (atom-text-editor.editor.is-focused)
  6x -8:54.9.0 core:move-down (atom-text-editor.editor.is-focused)
     -8:52.4.0 core:save (atom-text-editor.editor.is-focused)
  3x -8:45.4.0 core:close (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "audioBeep": false,
    "autoHideMenuBar": true,
    "closeEmptyWindows": false,
    "disabledPackages": [
      "wrap-guide"
    ],
    "excludeVcsIgnoredPaths": false,
    "ignoredNames": [
      "*.sql"
    ],
    "themes": [
      "one-dark-ui",
      "base16-tomorrow-dark-theme"
    ]
  },
  "imdone-atom": {
    "openIn": {},
    "todaysJournal": {}
  }
}
```
### Installed Packages

``` coffee
# User
autocomplete-sass, v0.1.0
autocomplete-wordpress-hooks, v0.2.0
clipboard-history, v0.6.6
docblockr, v0.7.3
emmet, v2.4.3
file-icons, v1.7.12
flex-tool-bar, v0.10.0
git-diff-details, v1.3.0
imdone-atom, v1.3.29
javascript-snippets, v1.2.1
jquery-snippets, v11.0.0
language-diff, v0.4.0
linter, v1.11.4
linter-jshint, v2.1.0
linter-php, v1.2.0
minimap, v4.24.0
package-sync, v1.1.0
pigments, v0.26.3
pinned-tabs, v0.2.2
project-manager, v2.9.7
symbols-tree-view, v0.12.0
tool-bar, v0.4.0
wordpress-dictionary, v4.4.0

# Dev
No dev packages
```

**Comment by piascikj** [comment]
Is this still an issue?

**Comment by onetrev** [comment]
Hmm, not sure. Unfortunately I've recently move on to VS Code so I can't double check any more either. Sorry. Probably safe to just close this I would say, because as much as I can remember it happening after this.
